### ISSUE TITLE
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by padamshrestha** [dotnet/tye#1046]
### Describe the bug
Error while running with dapr sample from sample
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

### To Reproduce
tye run

### Further technical details
**tye version** 
0.7.0-alpha.21257.1+0251fb2bb867ce37d96818a8034c0a05b9f93dca

**-v debug output**
c:\Projects\tye\samples\dapr\pub-sub>tye run -v debug
Loading Application Details...
Restoring and evaluating projects
Resolved metadata for service orders at c:\Projects\tye\artifacts\obj\orders\Debug\netcoreapp3.1\MicrosoftTye.ProjectMetadata.txt
Resolved metadata for service products at c:\Projects\tye\artifacts\obj\products\Debug\netcoreapp3.1\MicrosoftTye.ProjectMetadata.txt
Resolved metadata for service store at c:\Projects\tye\artifacts\obj\store\Debug\netcoreapp3.1\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 1677.4107ms
Found application version: 0.7.0-dev
RunCommand=c:\Projects\tye\samples\dapr\pub-sub\orders\bin\Debug\netcoreapp3.1\orders.exe
RunArguments=
TargetPath=c:\Projects\tye\samples\dapr\pub-sub\orders\bin\Debug\netcoreapp3.1\orders.dll
PublishDir=c:\Projects\tye\samples\dapr\pub-sub\orders\bin\Debug\netcoreapp3.1\publish\
AssemblyName=orders
IntermediateOutputPath=c:\Projects\tye\artifacts\obj\orders\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Parsed target framework name: netcoreapp
Parsed target framework version: 3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 3.9803ms
Found application version: 0.7.0-dev
RunCommand=c:\Projects\tye\samples\dapr\pub-sub\products\bin\Debug\netcoreapp3.1\products.exe
RunArguments=
TargetPath=c:\Projects\tye\samples\dapr\pub-sub\products\bin\Debug\netcoreapp3.1\products.dll
PublishDir=c:\Projects\tye\samples\dapr\pub-sub\products\bin\Debug\netcoreapp3.1\publish\
AssemblyName=products
IntermediateOutputPath=c:\Projects\tye\artifacts\obj\products\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Parsed target framework name: netcoreapp
Parsed target framework version: 3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1.9445ms
Found application version: 0.7.0-dev
RunCommand=c:\Projects\tye\samples\dapr\pub-sub\store\bin\Debug\netcoreapp3.1\store.exe
RunArguments=
TargetPath=c:\Projects\tye\samples\dapr\pub-sub\store\bin\Debug\netcoreapp3.1\store.dll
PublishDir=c:\Projects\tye\samples\dapr\pub-sub\store\bin\Debug\netcoreapp3.1\publish\
AssemblyName=store
IntermediateOutputPath=c:\Projects\tye\artifacts\obj\store\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Parsed target framework name: netcoreapp
Parsed target framework version: 3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1.5513ms
A 'placement-port' has not been defined. So the 'exclude-placement-container' will default to 'false'.
Injecting Dapr placement service...
Launching Tye Host...

[18:14:03 INF] Executing application from c:\Projects\tye\samples\dapr\pub-sub\tye.yaml
[18:14:03 INF] Dashboard running on http://127.0.0.1:8000
[18:14:04 INF] Docker image daprio/dapr already installed
[18:14:04 INF] Docker image redis already installed
[18:14:04 INF] Creating docker network tye_network_5e62962e-b
[18:14:04 INF] Running docker command network create --driver bridge tye_network_5e62962e-b
[18:14:04 INF] Running image redis for redis_8df7021a-f
[18:14:04 INF] Running image daprio/dapr for placement_b5a8454c-7
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for orders-proxy_806cb85b-d
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for products-proxy_38dd3fe3-4
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for store-proxy_c9cf1fa6-7
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for orders-dapr-proxy_3aa13ef6-2
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for products-dapr-proxy_19f050f9-c
[18:14:04 DBG] Running proxy image mcr.microsoft.com/dotnet/core/sdk:3.1 for store-dapr-proxy_8b08fea6-a
[18:14:04 INF] Building projects
[18:14:06 INF] Running container placement_b5a8454c-7 with ID fa44ef27a106
[18:14:06 INF] Replica placement_b5a8454c-7 is moving to a ready state
[18:14:06 INF] Collecting docker logs for placement_b5a8454c-7.
[18:14:06 INF] Launching service orders_e09764a9-7: c:\Projects\tye\samples\dapr\pub-sub\orders\bin\Debug\netcoreapp3.1\orders.exe
[18:14:06 INF] Launching service store-dapr_cba9349f-5: daprd -app-id store -app-port 54957 -dapr-grpc-port 54965 --dapr-http-port 54966 --metrics-port 54967 --placement-host-address localhost:54952 -log-level debug -components-path ./components/
[18:14:06 INF] Launching service products-dapr_5df9a25e-8: daprd -app-id products -app-port 54955 -dapr-grpc-port 54962 --dapr-http-port 54963 --metrics-port 54964 --placement-host-address localhost:54952 -log-level debug -components-path ./components/
[18:14:06 INF] Launching service store_b2c55000-8: c:\Projects\tye\samples\dapr\pub-sub\store\bin\Debug\netcoreapp3.1\store.exe
[18:14:06 INF] Launching service products_5d4cd3ac-d: c:\Projects\tye\samples\dapr\pub-sub\products\bin\Debug\netcoreapp3.1\products.exe
[18:14:06 INF] Launching service orders-dapr_d2bd9a49-b: daprd -app-id orders -app-port 54953 -dapr-grpc-port 54959 --dapr-http-port 54960 --metrics-port 54961 --placement-host-address localhost:54952 -log-level debug -components-path ./components/
[18:14:06 ERR] Failed to launch process for service store-dapr_cba9349f-5
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 132
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397
[18:14:06 ERR] Failed to launch process for service products-dapr_5df9a25e-8
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 132
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397
[18:14:06 INF] orders_e09764a9-7 running on process id 4772 bound to http://localhost:54953, https://localhost:54954
[18:14:06 INF] store_b2c55000-8 running on process id 43256 bound to http://localhost:54957, https://localhost:54958
[18:14:06 INF] products_5d4cd3ac-d running on process id 27480 bound to http://localhost:54955, https://localhost:54956

**Platform** 
WIndows

**Comment by padamshrestha** [comment]
Fixed with tye init

**Comment by andreatosato** [comment]
I have same problem

tye run -f net5.0

```
Loading Application Details...
Launching Tye Host...

[12:59:36 INF] Executing application from D:\GitHub\dapr-cloudchampion\tye.yaml
[12:59:36 INF] Dashboard running on http://127.0.0.1:8000
[12:59:37 INF] Docker image redis already installed
[12:59:37 INF] Docker image rabbitmq:3-management already installed
[12:59:37 INF] Docker image daprio/dapr already installed
[12:59:37 INF] removed container redis_4bb3fb2c-e from previous run
[12:59:37 INF] removed container rabbit_da380558-e from previous run
[12:59:38 INF] removed container placement_d10dec15-e from previous run
[12:59:38 INF] removed container cloudchampion-web-proxy_29f781e6-f from previous run
[12:59:39 INF] removed container cloudchampion-order-proxy_5c0e9351-4 from previous run
[12:59:40 INF] removed container cloudchampion-web-dapr-proxy_8d15f4f4-5 from previous run
[12:59:40 INF] removed container cloudchampion-order-dapr-proxy_ba5ce490-6 from previous run
[12:59:40 INF] Creating docker network tye_network_3871e027-2
[12:59:40 INF] Running docker command network create --driver bridge tye_network_3871e027-2
[12:59:41 INF] Running image redis for redis_b8d0ceb4-6
[12:59:41 INF] Running image rabbitmq:3-management for rabbit_652531f6-9
[12:59:41 INF] Running image daprio/dapr for placement_27d08928-7
[12:59:41 INF] removed process 21732 from previous run
[12:59:41 INF] removed process 23184 from previous run
[12:59:41 INF] Building projects
[12:59:42 ERR] docker run failed for rabbit with exit code 125: docker: Error response from daemon: driver failed programming external connectivity on endpoint rabbit_652531f6-9 (f3129cce9d3eb0382b38bb32827943c8cee7b39f01aa44d85db32a06f9fc707d): Bind for 0.0.0.0:5672 failed: port is already allocated.

[12:59:44 INF] Running container cloudchampion-web-dapr-proxy_c7d37dc9-4 with ID bdfc10bf67ac
[12:59:44 INF] Collecting docker logs for cloudchampion-web-dapr-proxy_c7d37dc9-4.
[12:59:44 INF] Running container cloudchampion-web-proxy_2d5ca5a9-3 with ID f2be75e4784c
[12:59:44 INF] Collecting docker logs for cloudchampion-web-proxy_2d5ca5a9-3.
[12:59:45 INF] Launching service cloudchampion-web_554452cf-f: D:\GitHub\dapr-cloudchampion\Frontend\CloudChampion.Web\bin\Debug\net5.0\CloudChampion.Web.exe 
[12:59:45 INF] Launching service cloudchampion-order-dapr_f037aba0-a: daprd -app-id cloudchampion-order -app-port 50162 -dapr-grpc-port 50167 --dapr-http-port 50168 --metrics-port 50169 --placement-host-address localhost:50159 -log-level debug -components-path ./dapr/components/
[12:59:45 INF] Launching service cloudchampion-web-dapr_7b58d2f1-0: daprd -app-id cloudchampion-web -app-port 50160 -dapr-grpc-port 50164 --dapr-http-port 50165 --metrics-port 50166 --placement-host-address localhost:50159 -log-level debug -components-path ./dapr/components/
[12:59:45 INF] Launching service cloudchampion-order_9783568a-7: D:\GitHub\dapr-cloudchampion\Services\CloudChampion.Order\bin\Debug\net5.0\CloudChampion.Order.exe 
[12:59:45 INF] cloudchampion-web_554452cf-f running on process id 22860 bound to http://localhost:50160, https://localhost:50161
[12:59:45 ERR] Failed to launch process for service cloudchampion-order-dapr_f037aba0-a
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397       
[12:59:45 ERR] Failed to launch process for service cloudchampion-web-dapr_7b58d2f1-0
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397       
[12:59:45 INF] cloudchampion-order_9783568a-7 running on process id 26200 bound to http://localhost:50162, https://localhost:50163
[12:59:45 INF] Replica cloudchampion-web_554452cf-f is moving to a ready state
[12:59:45 INF] Selected process 22860.
[12:59:45 INF] Running container redis_b8d0ceb4-6 with ID 17b937bc6d12
[12:59:45 INF] Replica cloudchampion-order_9783568a-7 is moving to a ready state
[12:59:45 INF] Selected process 26200.
[12:59:45 INF] Listening for event pipe events for cloudchampion-web_554452cf-f on process id 22860
[12:59:45 INF] Replica redis_b8d0ceb4-6 is moving to a ready state
[12:59:45 INF] Listening for event pipe events for cloudchampion-order_9783568a-7 on process id 26200
[12:59:45 INF] Collecting docker logs for redis_b8d0ceb4-6.
[12:59:45 INF] Running container placement_27d08928-7 with ID a464f326c93e
[12:59:45 INF] Replica placement_27d08928-7 is moving to a ready state
[12:59:45 INF] Collecting docker logs for placement_27d08928-7.
[12:59:45 INF] Running container cloudchampion-order-dapr-proxy_8f97d681-1 with ID 39548acdf1ce
[12:59:45 INF] Collecting docker logs for cloudchampion-order-dapr-proxy_8f97d681-1.
[12:59:46 INF] Running container cloudchampion-order-proxy_2b87b7e9-9 with ID 5549a3d305b8
[12:59:46 INF] Collecting docker logs for cloudchampion-order-proxy_2b87b7e9-9.
[12:59:55 INF] Launching service cloudchampion-order-dapr_361bcdf5-7: daprd -app-id cloudchampion-order -app-port 50162 -dapr-grpc-port 50167 --dapr-http-port 50168 --metrics-port 50169 --placement-host-address localhost:50159 -log-level debug -components-path ./dapr/components/
[12:59:55 ERR] Failed to launch process for service cloudchampion-order-dapr_361bcdf5-7
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397       
[12:59:55 INF] Launching service cloudchampion-web-dapr_83dd0bad-a: daprd -app-id cloudchampion-web -app-port 50160 -dapr-grpc-port 50164 --dapr-http-port 50165 --metrics-port 50166 --placement-host-address localhost:50159 -log-level debug -components-path ./dapr/components/
[12:59:55 ERR] Failed to launch process for service cloudchampion-web-dapr_83dd0bad-a
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397       
```

```YAML
name: cloudchampion
extensions:
   - name: dapr
     log-level: debug
     components-path: "./dapr/components/"
services:
- name: cloudchampion-web
  project: Frontend/CloudChampion.Web/CloudChampion.Web.csproj
  env:
  - ASPNETCORE_ENVIRONMENT=Development
  - ASPNETCORE_URLS=http://+:80
- name: cloudchampion-order
  project: Services/CloudChampion.Order/CloudChampion.Order.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}" 
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
      protocol: rabbitmq
```

**Comment by padamshrestha** [comment]
I think my issue was switching between WSL and non-WSL mode. Tye doesn't seem to initialize Dapr automatically. So you might need to 'dapr init' explicitly.

**Comment by andreatosato** [comment]
I open #1089 

I have already run DAPR INIT
