### ISSUE TITLE
Tye crashes when shutting down configuration with many services

### ISSUE THREAD

**Issue by Kralizek** [dotnet/tye#1088]
### Describe the bug
When shutting down tye, I get the following error

```
[15:56:39 ERR] Error while shutting down
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.
   at Bedrock.Framework.TimerAwaitable.Stop()
   at Bedrock.Framework.Server.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Tye.Hosting.ProxyService.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/ProxyService.cs:line 190
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 315
Oh dear! Operation canceled.
```

### To Reproduce
I got a configuration with:
- 1 razor page app
- 1 web api app
- 14 grpc services
- 1 container

To reproduce
```sh
$ tye run
<< CTRL C >>
```

I can't reproduce it consistently

### Further technical details

- Include the output of `tye --version`
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)

```sh
$ tye --version
0.6.0-alpha.21070.5+a42e4463943e3136dbd1de38474d8d62b802797c
```

**Comment by ikkentim** [comment]
This problem was solved in 0.7, which has already been release. 
Update with

dotnet tool update -g Microsoft.Tye --version "0.7.0-alpha.21279.2"

**Comment by Kralizek** [comment]
Thanks @ikkentim
