### ISSUE TITLE
Failed to launch process for service - No such file or directory

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/tye#1145]
Tye stopped working after update, which should not affect this.

I installed the latest preview of .NET 6 SDK Preview 7 x64 on my M1 Mac, and updated the Tye Global tools like so:

```
robert@RobertsMBPWork Commerce % dotnet tool update -g Microsoft.Tye --version "0.9.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

Tool 'microsoft.tye' was reinstalled with the latest stable version (version '0.9.0-alpha.21380.1').
```

My projects is targeting .NET 5:

I ran ```tye run```:

```
[11:23:55 INF] watch: commerce-api_bf824114-7 Started
[11:23:55 ERR] Failed to launch process for service commerce-api_bf824114-7
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 147
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, String replica, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs:line 72
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 380
[11:23:55 INF] Tye Host is stopping...
```

My projects targets .NET 5:

My ```global.json```:

```
{
    "sdk": {
      "version": "5.0.400"
    }
  }
```

**Comment by robertsundstrom** [comment]
I uninstalled  NET 6 SDK Preview 6 and 7, it works again.

**Comment by fleed** [comment]
Same problem with the latest version to date:

- .net: **SDK 6.0.100-rc.1**
- Tye: **0.10.0-alpha.21420.1**

Tested on a **MacOS 11.6**

**Comment by TheAngryByrd** [comment]
Same problem with 6.0.100 released

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.5
 OS Platform: Darwin
 RID:         osx.11.0-x64

**Comment by TheAngryByrd** [comment]
Working with @baronfel, he suggested adding [UseAppHost](https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues#apphost-is-disabled-by-default) as a work around.

```xml
<PropertyGroup>
    <UseAppHost>true</UseAppHost>
</PropertyGroup>
```

It seems to work for me.

**Comment by baronfel** [comment]
I think this is because of the change to revert the AppHost as the default build output for MacOS.  Project Reading derives the `RunCommand` from build metadata [here](https://github.com/dotnet/tye/blob/main/src/Microsoft.Tye.Core/ProjectReader.cs#L108), which should be the apphost executable, but on MacOS on .NET 6+ we do not create the AppHost due to signing issues. This means that the RunCommand is incorrect, and thus the service cannot be launched.
