### ISSUE TITLE
az-function not working with dotnet 6 and azure-functions-core-tools@4

### ISSUE THREAD

**Issue by padamshrestha** [dotnet/tye#1241]
### Describe the bug
System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/local/Cellar/azure-functions-core-tools@3'.
The functions work without tye.

### To Reproduce
It's happening with dotnet 6 and azure-functions-core-tools@4. 

20:32:54 INF] Dashboard running on http://127.0.0.1:8000
An unhandled exception has occurred, how unseemly: 
System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/local/Cellar/azure-functions-core-tools@3'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetDirectories(String path)
   at Microsoft.Tye.Hosting.FuncFinder.FuncDllPath() in /_/src/Microsoft.Tye.Hosting/FuncFinder.cs:line 89
   at Microsoft.Tye.Hosting.FuncFinder.FindFuncForVersion(AzureFunctionRunInfo func) in /_/src/Microsoft.Tye.Hosting/FuncFinder.cs:line 53
   at Microsoft.Tye.Hosting.FuncFinder.StartAsync(Application application) in /_/src/Microsoft.Tye.Hosting/FuncFinder.cs:line 45
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StartAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 26
   at Microsoft.Tye.Hosting.TyeHost.StartAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 120
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 68
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 80
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location ---
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
### Further technical details

- Include the output of `tye --version`
0.11.0-alpha.21611.1+9aa4f690bbfd3a3abcf2e946d9459ee7021fab8f
- Platform
MacOS armx64 m1

**Comment by philliphoff** [comment]
@padamshrestha Tye is indeed currently tied to Azure Functions v3 in how it finds the Functions core host assembly, at least on non-Windows machines.  That can certainly be fixed.  The not-so-good news is that the Functions core tools does not yet support `arm64` (i.e. M1) machines (see [azure-functions-core-tools#2834](https://github.com/Azure/azure-functions-core-tools/issues/2834)), so even changes are made to Tye to support v4, you'll still be waiting to use it with an M1 machine.
