### ISSUE TITLE
Github Actions Tye push

### ISSUE THREAD

**Issue by SpeedySDK** [dotnet/tye#1278]
I better start by saying i'm still learning github actions and this could be my innability to configure the yaml. 
I have an API in .net 6 and i'm trying to use Actions CI to do "tye push tye.yaml". (tye latest version "0.2.0-alpha.20258.3"). It works fine locally.

This is the push part of my pipeline:

```
deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Install tye
      run: dotnet tool install -g Microsoft.Tye --version "0.2.0-alpha.20258.3"
    - name: List Runtimes
      run: dotnet --list-runtimes
    - name: Push to DockerHub
      run: tye push tye.yaml
```

Here's the output:

```
Run tye push tye.yaml
  tye push tye.yaml
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /home/runner/.dotnet
Loading Application Details...
An unhandled exception has occurred, how unseemly: 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Tye.ProjectReader.EvaluateProject(OutputContext output, ProjectServiceBuilder project)
   at Microsoft.Tye.ProjectReader.ReadProjectDetailsAsync(OutputContext output, ProjectServiceBuilder project) in /_/src/Microsoft.Tye.Core/ProjectReader.cs:line 80
   at Microsoft.Tye.ApplicationFactory.CreateAsync(OutputContext output, FileInfo source) in /_/src/Microsoft.Tye.Core/ApplicationFactory.cs:line 99
```

**Comment by samtrion** [comment]
The version of Tye you are using `0.2.0-alpha.20258.3` does not support .NET 6. Therefore you should switch to .NET 5 and especially update the Tye version.

**Comment by SpeedySDK** [comment]
Thank you. Didn't realise i was using 0.10 locally and 0.2 in the pipeline. Stupid mistake xD
