### ISSUE TITLE
Issues with kubernetes client failing to access cluster during secrets

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#128]
### Describe the bug
I've been having issues when running `tye deploy` and when trying to check kubernetes secrets, I get an error:

```
Reading Project Details...
Reading Project Details...
Reading Project Details...
Enter the Container Registry (ex: 'example.azurecr.io' for Azure or 'example' for dockerhub): jkotalik
Processing Service 'backend'...
    Compiling Services...
    Publishing Project...
        Created Publish Output: 'C:\Users\jukotali\code\tye\samples\multi-project\backend\bin\Release\netcoreapp3.1\pub
    Building Docker Image...
        Created Docker Image: 'jkotalik/backend:0.1.0-dev'

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest,
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncR
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction,                            tion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOp                               --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOp                               at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken canc
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellat
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, Cancella
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationToken
   at k8s.Kubernetes.ReadNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 exact                            ry`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Tye.ValidateSecretStep.ExecuteAsync(OutputContext output, Application application, ServiceEntry service                            t.Tye.Core\ValidateSecretStep.cs:line 65
```

I didn't have this issue before, but seems like potentially a common issue people may hit. Our current hypothesis for what is wrong is potentially an issue with the kubernetes c# client, but we aren't sure yet.

Let's see if other people hit this issue as well.

**Comment by rynowak** [comment]
As @jkotalik - we're curious to see if this is just an issue on his machine or if other people hit it as well.

**Comment by rynowak** [comment]
@jkotalik - if this is still a problem please reactivate. We haven't seen any other reports of this.
