### ISSUE TITLE
Tye runtime exception

### ISSUE THREAD

**Issue by mpp** [dotnet/tye#1321]
### Describe the bug
Hi! I'm getting this runtime exception.
The application is an Asp.Net core minimal API with .net6.
```
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
SpanId: e9324023ae0b87dd
TraceId: 78d1192ae9bd7c420cb51527541e8db0
ParentId: 0000000000000000
ConnectionId: 0HMFRHON9DCAF
RequestId: 0HMFRHON9DCAF:00000009
RequestPath: /Alarms/Active

Connection id "0HMFRHON9DCAF", Request id "0HMFRHON9DCAF:00000009": An unhandled exception was thrown by the application.

Exception: 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Tye.Hosting.ConnectionRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Infrastructure/ConnectionRetryHandler.cs:line 37
   at Microsoft.AspNetCore.Proxy.ProxyAdvancedExtensions.ProxyRequest(HttpContext context, HttpMessageInvoker invoker, Uri destinationUri) in /_/src/Microsoft.Tye.Hosting/Infrastructure/ProxyExtensions.cs:line 43
   at Microsoft.Tye.Hosting.HttpProxyService.<>c__DisplayClass4_4.<<StartAsync>b__9>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/HttpProxyService.cs:line 185
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Do you have any suggestion on how to better handle it?
Should I put a try-catch on every endpoint mapped by the minimal API?

Thanks

### Further technical details
- Version: 
```
>tye --version
0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600
```
- The platform (Linux/macOS/Windows): Windows

**Comment by davidfowl** [comment]
Can you provide a repro?

**Comment by mpp** [comment]
@davidfowl it will take me some time, if you want go ahead and close the issue.
I'll reopen it when I'll get a working repro with no sensible code in it.

Thanks
