### ISSUE TITLE
Tye and Dapr Secret Store Integration Problem

### ISSUE THREAD

**Issue by pirimoglu** [dotnet/tye#1374]
### Describe the bug
I try to use tye with dapr. I add secret store feature to dapr, but with using tye I get an error, Out of tye (with only docker compose) I can use this feature

`
[sampleservice_888cff5e-3]: Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
[sampleservice_888cff5e-3]: at Dapr.Client.DaprClientGrpc.WaitForSidecarAsync(CancellationToken cancellationToken)
[sampleservice_888cff5e-3]: at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()
[sampleservice_888cff5e-3]: at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()
[sampleservice_888cff5e-3]: at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
[sampleservice_888cff5e-3]: at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
[sampleservice_888cff5e-3]: at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
[sampleservice_888cff5e-3]: at Microsoft.Extensions.Hosting.HostBuilder.Build()
`

### To Reproduce
I used below code blocks.
https://github.com/dapr/dotnet-sdk/blob/master/examples/AspNetCore/SecretStoreConfigurationProviderSample/Program.cs

### Further technical details
tye --version
0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600

Op. System
Windows 10

**Comment by Phiph** [comment]
Hi @pirimoglu 

What secret store are you using? Have you appropriately set up a component, and referenced that folder in your tye file?

Do you have an example repo for me to look at?
