### ISSUE TITLE
Subject is not thread safe

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#179]
### Describe the bug

Seen this once:

### To Reproduce
```
Unhandled exception. System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter '
destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Microsoft.Tye.Hosting.Model.Service.<.ctor>b__0_0(String entry) in C:\dev\git\tye\src\Microsoft.Tye.Hosting\Model\Service.cs:line 25
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass6_2.<LaunchService>b__5(String data) in C:\dev\git\tye\src\Microsoft.Tye.Hosting\ProcessRunner.cs:line 201
   at Microsoft.Tye.ProcessUtil.<>c__DisplayClass1_0.<RunAsync>b__0(Object _, DataReceivedEventArgs e) in C:\dev\git\tye\src\Microsoft.Tye.Core\ProcessUtil.cs:line 6
6
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### Further technical details

Saw it on shutdown, on windows in one of my branches.

**Comment by rynowak** [comment]
Should we be using a channel instead? I haven't dug into the rx code that you put here much, but it seems like we're not using much of their feature set.

**Comment by davidfowl** [comment]
We're not using Rx per se but we need a way to do events for things like server side blazor. The data models or something around the data model needs to tell various pieces of the system when they have changed to do things like inject "side cars", clean up state, update some UI etc.

Channel wouldn't work well here because we need multiple consumers for the same event.

**Comment by davidfowl** [comment]
I think I'm wrong about subject, it's the code inside one of the callbacks that is unsafe 😄 .
