### ISSUE TITLE
Build and run issue with frontend/backend sample

### ISSUE THREAD

**Issue by QueenCitySmitty** [dotnet/tye#194]
### Describe the bug
I'm following through the [Frontend-Backend Sample](https://github.com/dotnet/tye/blob/master/docs/frontend_backend_run.md), and every time I'm using ``dotnet new ..`` then ``tye run ..``, I'm getting this error:

```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 110
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass6_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 186
```

When I close the window, then reopen and try the command again it works.  

tye version: 0.1.0-alpha.20168.8+f45b9444d4894009bde48e2a3411a52dd09497b1
dotnet: 5.0.100-preview.1.20104.11
Windows

**Comment by rynowak** [comment]
Thanks for reporting this. Sorry you ran into problems. @davidfowl - any ideas about how to investigate?

**Comment by davidfowl** [comment]
Open up the dashboard and look at the logs for the services, and paste it in here.

**Comment by QueenCitySmitty** [comment]
dotnet build "c:\repos\microservice2\frontend\frontend.csproj" /nologo
Restore completed in 32.22 ms for c:\repos\microservice2\frontend\frontend.csproj.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
frontend -> c:\repos\microservice2\frontend\bin\Debug\netcoreapp5.0\frontend.dll
frontend -> c:\repos\microservice2\frontend\bin\Debug\netcoreapp5.0\frontend.Views.dll
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:01.42
[frontend_103321ac-6]:c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe
[frontend_cf8db7b7-d]:c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe
[frontend_4d8f95af-b]:c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe

**Comment by davidfowl** [comment]
Can you also send the logs from `tye run` itself?

**Comment by QueenCitySmitty** [comment]
c:\repos\microservice2>tye run frontend
[23:31:27 INF] Executing application from c:\repos\microservice2\frontend\frontend.csproj
[23:31:27 INF] Default dashboard port 8000 is in use, choosing random port.
[23:31:27 INF] Dashboard running on http://127.0.0.1:51553
[23:31:27 INF] Building project c:\repos\microservice2\frontend\frontend.csproj
[23:31:31 INF] Launching service frontend_9225cf62-1: c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe
[23:31:32 ERR] Failed to launch process for service frontend_9225cf62-1
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 110
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass6_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 186
[23:31:37 INF] Launching service frontend_26bf4d63-5: c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe

**Comment by davidfowl** [comment]
Does this file exist? `c:\repos\microservice2\frontend\bin\Debug\netcoreapp3.1\frontend.exe` ?

**Comment by QueenCitySmitty** [comment]
I'm using dotnet 5.0 right now, so I have the netcoreapp5.0 folder.  Let me try uninstalling dotnet 5, since the instructions do say use 3.1.

**Comment by davidfowl** [comment]
@QueenCitySmitty I see, we're not finding the right folder. That's the issue, this is fixed in the latest CI build but not in the one linked in the tutorial. Using netcoreapp3.1 should work for now.

**Comment by QueenCitySmitty** [comment]
@davidfowl yep when I went back to 3.1.201, it worked first time.  Awesome, thanks all.
