### ISSUE TITLE
EventPipe exception on shutdown 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#212]
### Describe the bug
Saw this on shutdown:

```
[19:32:41 DBG] Failed to start the event pipe session
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.Write(Stream stream, Byte[] buffer)
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.Write(Stream stream, IpcMessage message)
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessage(Int32 processId, IpcMessage message, IpcMessage& respo
nse)
   at Microsoft.Diagnostics.NETCore.Client.EventPipeSession..ctor(Int32 processId, IEnumerable`1 providers, Boolean req
uestRundown, Int32 circularBufferMB)
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.StartEventPipeSession(IEnumerable`1 providers, Boolean req
uestRundown, Int32 circularBufferMB)
   at Microsoft.Tye.Hosting.Diagnostics.DiagnosticsCollector.ProcessEvents(String applicationName, String serviceName,
Int32 processId, String replicaName, IDictionary`2 metrics, CancellationToken cancellationToken) in C:\dev\git\tye\src\
Microsoft.Tye.Hosting.Diagnostics\DiagnosticsCollector.cs:line 198
```

### To Reproduce
Happens randomly on shutdown.

**Comment by jkotalik** [comment]
This log is at debug level, should we just suppress the log entirely?

**Comment by davidfowl** [comment]
Yep

**Comment by rynowak** [comment]
Fixed right?

**Comment by jkotalik** [comment]
Dang, I thought the word "For X" would work, guess I won't.
