### ISSUE TITLE
Docker services are not working

### ISSUE THREAD

**Issue by alexfdezsauco** [dotnet/tye#277]
### Describe the bug

Docker services are not working in the latest CI build with error  `Property 'dockerImage' not found on type 'Microsoft.Tye.ConfigModel.ConfigService'`.

### To Reproduce

1) Just create a `tye.yml` file and add a docker service entry like this one.

          - name: dti-systems-keycloak
          dockerImage: jboss/keycloak:6.0.1
          bindings:
            - port: 5004

2) run `try run`

**Log:** 

    An unhandled exception has occurred, how unseemly:
    YamlDotNet.Core.YamlException: (Line: 31, Col: 3, Idx: 1374) - (Line: 31, Col: 3, Idx: 1374): Exception during deserialization
     ---> System.Runtime.Serialization.SerializationException: Property 'dockerImage' not found on type 'Microsoft.Tye.ConfigModel.ConfigService'.
       at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
       at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
       --- End of inner exception stack trace ---
       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
       at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)

       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
       at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
       at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
       at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)

       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
       at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
       at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
       at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)

       at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
       at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
       at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
       at Microsoft.Tye.ConfigModel.ConfigFactory.FromYaml(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 80
       at Microsoft.Tye.ConfigModel.ConfigFactory.FromFile(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 30
       at Microsoft.Tye.ApplicationFactory.CreateAsync(OutputContext output, FileInfo source) in /_/src/Microsoft.Tye.Core/ApplicationFactory.cs:line 24
       at Microsoft.Tye.Program.<>c__DisplayClass9_0.<<CreateRunCommand>b__0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 76
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
       at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
       at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

### Further technical details

- **tye version** : 0.1.0-alpha.20180.5+36b0c0e2113a52a2ec4eb1ab8d0c300dadc1cc13
- **Platform**: Windows

**Comment by jkotalik** [comment]
`dockerImage` got renamed to `image`. We are also in the process of improving the error message for deserialization errors.

**Comment by alexfdezsauco** [comment]
Sorry, my mistake
