### ISSUE TITLE
tye deploy does not work if KUBECONFIG has more than one entry

### ISSUE THREAD

**Issue by giggio** [dotnet/tye#351]
### Describe the bug

When the env var `KUBECONFIG` is set to more than one file, `tye deploy` fails.

On Windows pwsh, simply set it like this:

````pwsh
$env:KUBECONFIG="$env:USERPROFILE\.kube\config;$env:USERPROFILE\.kube\other-config"
````

This is the log after running `tye deploy --interactive`, using the second [step of tutorial](https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/02_add_redis.md#deploying-redis).

````
Loading Application Details...
Processing Service 'frontend'...
    Compiling Services...
    Publishing Project...
    Building Docker Image...
        Created Docker Image: 'giggio/frontend:1.0.0'
    Pushing Docker Image...
        Pushed docker image: 'giggio/frontend:1.0.0'
    Validating Secrets...
An unhandled exception has occurred, how unseemly:
k8s.Exceptions.KubeConfigException: kubeconfig file not found at C:\Users\giovanni\.kube\config;C:\Users\giovanni\.kube\other-config;
   at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.LoadKubeConfig(FileInfo kubeconfig, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildDefaultConfig()
   at Microsoft.Tye.ValidateSecretStep.ExecuteAsync(OutputContext output, ApplicationBuilder application, ServiceBuilder service) in /_/src/Microsoft.Tye.Core/ValidateSecr
etStep.cs:line 54
   at Microsoft.Tye.ServiceExecutor.ExecuteAsync(ServiceBuilder service) in /_/src/Microsoft.Tye.Core/ServiceExecutor.cs:line 50
   at Microsoft.Tye.Program.ExecuteDeployAsync(OutputContext output, ApplicationBuilder application, String environment, Boolean interactive, Boolean force) in /_/src/tye/
Program.DeployCommand.cs:line 86
   at Microsoft.Tye.Program.<>c.<<CreateDeployCommand>b__3_0>d.MoveNext() in /_/src/tye/Program.DeployCommand.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
````

### Further technical details

- Include the output of `tye --version`: `0.1.0-alpha.20209.5+e3fc0045bd1e5913da935241874761929f1e8465`
- The platform (Linux/macOS/Windows): Windows

**Comment by rynowak** [comment]
Thanks for reporting. I'll take a look at this.

**Comment by rynowak** [comment]
It looks like this is a bug in the upstream kubernetes client: https://github.com/kubernetes-client/csharp/issues/409

I'll see if I can work around it.

**Comment by rynowak** [comment]
@giggio - we're looking at trying to contribute a fix for this upstream. Do you mind telling us a little bit about why you have multiple config files? We want to make sure we address your scenario.

**Comment by giggio** [comment]
I work with different customers and most of them ask me to renew my configs everyday, and I separate them in different files.
Also, some projects use automation to get the configs and drop them on a config file on the project directory.
Also, Docker for Windows sometimes resets the local cluster config. When that happens I have to copy over the default kube config file from Windows to WSL (which is where I do most of my k8s work), so I don't like to change the default file at all.
When a project ends, it's easy to remove the cluster info, I just delete the file.
Usually I have lots of config files at ~/.kube, and I have scripts for Bash and PowerShell that compose the KUBECONFIG environment variable on shell start up.

**Comment by rynowak** [comment]
Thanks, that helps!

**Comment by rynowak** [comment]
We've fixed this upstream - we'll see when we can get a new build of the k8s client and test this out.

**Comment by rynowak** [comment]
There should hopefully be a build that has this fix.
