### ISSUE TITLE
Connection refused when running `tye run`

### ISSUE THREAD

**Issue by giggio** [dotnet/tye#354]
### Describe the bug
If you `tye run` you get `SocketException: Connection refused`

This is the log after running `tye run --docker`, using the second [step of tutorial](https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/02_add_redis.md#deploying-redis).

Console logs:

````
▶ tye run --docker
Loading Application Details...
Launching Tye Host...

[16:11:34 INF] Executing application from C:\p\rabiscos\tye\trytye\microservice\tye.yaml
[16:11:35 INF] Dashboard running on http://127.0.0.1:8000
[16:11:35 INF] Publishing project C:\p\rabiscos\tye\trytye\microservice\frontend\frontend.csproj
[16:11:35 INF] Publishing project C:\p\rabiscos\tye\trytye\microservice\backend\backend.csproj
[16:11:40 INF] Docker image mcr.microsoft.com/dotnet/core/sdk:3.1 already installed
[16:11:40 INF] Docker image redis:alpine already installed
[16:11:40 INF] Creating docker network tye_network_d531406b-6
[16:11:40 INF] Running docker command network create --driver bridge tye_network_d531406b-6
[16:11:41 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for frontend_72f9bbf8-e
[16:11:41 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for backend_583c1456-2
[16:11:41 INF] Running image redis:alpine for redis_4c783cbf-0
[16:11:41 INF] Running image redis:alpine for redis-cli_51993053-7
[16:11:42 INF] Running container redis_4c783cbf-0 with ID acc58b805a49
[16:11:42 INF] Running docker command network connect tye_network_d531406b-6 redis_4c783cbf-0 --alias redis
[16:11:42 INF] Running container redis-cli_51993053-7 with ID ccf2a3b3b8b4
[16:11:42 INF] Running docker command network connect tye_network_d531406b-6 redis-cli_51993053-7 --alias redis-cli
[16:11:43 INF] Collecting docker logs for redis_4c783cbf-0.
[16:11:43 INF] Collecting docker logs for redis-cli_51993053-7.
[16:11:45 INF] Running container frontend_72f9bbf8-e with ID 7bd5ae7a1e95
[16:11:45 INF] Running docker command network connect tye_network_d531406b-6 frontend_72f9bbf8-e --alias frontend
[16:11:45 INF] Collecting docker logs for frontend_72f9bbf8-e.
[16:11:47 INF] Running container backend_583c1456-2 with ID 405601e41f91
[16:11:47 INF] Running docker command network connect tye_network_d531406b-6 backend_583c1456-2 --alias backend
[16:11:47 INF] Collecting docker logs for backend_583c1456-2.
````

Exception log on page;

````
System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at frontend.WeatherClient.GetWeatherAsync() in C:\p\rabiscos\tye\trytye\microservice\frontend\WeatherClient.cs:line 24
   at frontend.Pages.IndexModel.OnGet(WeatherClient client) in C:\p\rabiscos\tye\trytye\microservice\frontend\Pages\Index.cshtml.cs:line 23
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
````

This is `tye.yaml`:

````yaml
name: microservice
registry: giggio
services:
  - name: frontend
    project: frontend/frontend.csproj
  - name: backend
    project: backend/backend.csproj
  - name: redis
    image: redis:alpine
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"
  - name: redis-cli
    image: redis:alpine
    args: "redis-cli -h redis MONITOR"
````

### Further technical details

- Include the output of `tye --version`: `0.1.0-alpha.20209.5+e3fc0045bd1e5913da935241874761929f1e8465`
- If possible rerun the command with `-v debug` and include the output: (not available with `tye run`)
- The platform (Linux/macOS/Windows): Windows

**Comment by rynowak** [comment]
I can reproduce this on macOS also

**Comment by rynowak** [comment]
I think I have an understanding of the issue. Some archeology...

The service discovery env-vars point `frontend`->`backend` via `https://backend:80`

Attaching a shell to `frontend` and seeing if we can talk to the backend:

```sh
docker exec -it frontend_c37fa3d9-7 bash
curl http://backend:80/weatherforecast -v
```

```txt
< HTTP/1.1 307 Temporary Redirect
< Date: Fri, 10 Apr 2020 20:40:01 GMT
< Server: Kestrel
< Content-Length: 0
< Location: https://backend:55643/weatherforecast
```

```sh
curl https://backend:55643/weatherforecast -v --insecure
```

Gets me a connection-refused.

```sh
curl https://backend:443/weatherforecast -v --insecure
```

Gets me the actual data.

--- 

In this case the https redirect uses 55643 based on the value passed in by Tye of [`HTTPS_PORT`](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio). However there's a problem with that. The port you want to redirect to is contexutal depending on who's asking.

If the request came from inside the container network then `443` is the right answer, if it came from outside the container network then `55643` is the right answer.

**Comment by rynowak** [comment]
@davidfowl

**Comment by davidfowl** [comment]
UGH 😄

**Comment by jkotalik** [comment]
The fix here is to revert back to the docker host instead of container names.
