### ISSUE TITLE
Error on tye run with a Docker folder on project solution

### ISSUE THREAD

**Issue by adiazcan** [dotnet/tye#363]
### Describe the bug
We have a problem when we run tye run with a custom tye.yaml and in the folder we have a "Docker" folder. 

We found the following Exception:

An unhandled exception has occurred, how unseemly:
System.UnauthorizedAccessException: Access to the path 'C:\git\tc\BackEnd\ENC.TEAMSCHAMP\docker' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Microsoft.Tye.Hosting.ReplicaRegistry.DeleteStore(String storeName) in /_/src/Microsoft.Tye.Hosting/ReplicaRegistry.cs:line 62
   at Microsoft.Tye.Hosting.DockerRunner.PurgeFromPreviousRun() in /_/src/Microsoft.Tye.Hosting/DockerRunner.cs:line 469
   at Microsoft.Tye.Hosting.DockerRunner.StartAsync(Application application) in /_/src/Microsoft.Tye.Hosting/DockerRunner.cs:line 37
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StartAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicati
onProcessor.cs:line 24
   at Microsoft.Tye.Hosting.TyeHost.StartAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 104
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 70
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 76
   at Microsoft.Tye.Program.<>c__DisplayClass9_0.<<CreateRunCommand>b__0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Tye.Program.<>c__DisplayClass9_0.<<CreateRunCommand>b__0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

### To Reproduce
1. Create a "Docker" folder in the same folder that we have the tye.yaml file and the other projects folder. 
2. Run tye run 

You will find the following exception:

![image](https://user-images.githubusercontent.com/6652046/79163547-93daf200-7ddf-11ea-9f7d-911369127e18.png)

### Further technical details
- Include the output of `tye --version`
0.1.0-alpha.20209.5+e3fc0045bd1e5913da935241874761929f1e8465
0.2.0-alpha.20212.1+a55639072e3b0f17cfe9fdf1e243c4dd61993731
- The platform (Linux/macOS/Windows)
Windows

**Comment by santypr** [comment]
Same issue here. I could reproduce it and my tye version is 0.1.0-alpha.20209.5+e3fc0045bd1e5913da935241874761929f1e8465

**Comment by davidfowl** [comment]
Hmm, do you have a .tye folder next to the solution?

**Comment by davidfowl** [comment]
Oh wait I just saw the repro, I'll take a look.

**Comment by santypr** [comment]
Great!
