### ISSUE TITLE
Tye 0.2.* and 0.3.* with Dapr extension isn't working

### ISSUE THREAD

**Issue by thangchung** [dotnet/tye#482]
### Describe the bug

`tye` `0.3.0-alpha.20265.1+ef441e87047930e04d24646e0d89183b07552747` with `dapr extensions` isn't working, and the the same issue with `tye` `0.2.0-alpha.20258.3`

### To Reproduce

I upgraded my practical-dapr project to use `tye` 0.3 following the guidance document at https://github.com/dotnet/tye/blob/master/docs/getting_started.md#working-with-ci-builds, as below

```
$ dotnet tool install -g Microsoft.Tye --version "0.3.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
```

Everything was working after I adapted my code with the `tye` tool at version 0.3.
But when I added `dapr extensions` config as below

```yaml
extensions:
- name: dapr
  log-level: debug
```

Then all worked projects above couldn't run anymore

![image](https://user-images.githubusercontent.com/422341/82119997-1f63ec00-97ad-11ea-82fd-6dee0bf29f6b.png)

After I cancelled `tye CLI` it threw the exception

```
# tye run
Loading Application Details...
Launching Tye Host...

[19:48:59 INF] Executing application from D:\github\practical-dapr\tye.yaml
[19:49:00 INF] Dashboard running on http://127.0.0.1:8000
[19:49:00 INF] Docker image mcr.microsoft.com/mssql/server:2017-latest already installed
[19:49:00 INF] Docker image redis already installed
[19:49:00 INF] Creating docker network tye_network_8c0faa56-4
[19:49:00 INF] Running docker command network create --driver bridge tye_network_8c0faa56-4
[19:49:01 INF] Running image mcr.microsoft.com/mssql/server:2017-latest for sqlserver_98aff541-2
[19:49:01 INF] Running image redis for redis_3a1d29cb-6
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for graphapi-proxy_412bbd63-a
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for identityserver-proxy_e3751a17-f
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for productcatalogapi-proxy_11e14a58-6
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for inventoryapi-proxy_2b78b28c-0
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for webuihost-proxy_cd947ec2-4
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for graphapi-dapr-proxy_aa1a07ae-1
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for identityserver-dapr-proxy_60c7074b-c
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for productcatalogapi-dapr-proxy_b75974b4-0
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for inventoryapi-dapr-proxy_a1fcccbb-5
[19:49:01 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for webuihost-dapr-proxy_26ac3bed-f
[19:49:01 INF] Building projects
[19:49:03 INF] Running container sqlserver_98aff541-2 with ID 163fda6e3456
[19:49:03 INF] Running docker command network connect tye_network_8c0faa56-4 sqlserver_98aff541-2 --alias sqlserver
[19:49:03 INF] Running container graphapi-proxy_412bbd63-a with ID 9c43b9bc009f
[19:49:03 INF] Running docker command network connect tye_network_8c0faa56-4 graphapi-proxy_412bbd63-a --alias graphapi
[19:49:03 INF] Running container identityserver-proxy_e3751a17-f with ID 6a735b92d82c
[19:49:03 INF] Running docker command network connect tye_network_8c0faa56-4 identityserver-proxy_e3751a17-f --alias identityserver
[19:49:03 INF] Running container productcatalogapi-proxy_11e14a58-6 with ID 10c17a97090a
[19:49:03 INF] Running docker command network connect tye_network_8c0faa56-4 productcatalogapi-proxy_11e14a58-6 --alias productcatalogapi
[19:49:05 INF] Collecting docker logs for sqlserver_98aff541-2.
[19:49:05 INF] Running container redis_3a1d29cb-6 with ID fe033e1ddc0c
[19:49:05 INF] Running docker command network connect tye_network_8c0faa56-4 redis_3a1d29cb-6 --alias redis
[19:49:05 INF] Running container inventoryapi-proxy_2b78b28c-0 with ID e09ede1a1c17
[19:49:05 INF] Running docker command network connect tye_network_8c0faa56-4 inventoryapi-proxy_2b78b28c-0 --alias inventoryapi
[19:49:05 INF] Collecting docker logs for graphapi-proxy_412bbd63-a.
[19:49:06 INF] Running container webuihost-proxy_cd947ec2-4 with ID 0240970bf67e
[19:49:06 INF] Running docker command network connect tye_network_8c0faa56-4 webuihost-proxy_cd947ec2-4 --alias webuihost
[19:49:06 INF] Collecting docker logs for productcatalogapi-proxy_11e14a58-6.
[19:49:06 INF] Collecting docker logs for identityserver-proxy_e3751a17-f.
[19:49:07 INF] Running container graphapi-dapr-proxy_aa1a07ae-1 with ID 11e4ce241c7f
[19:49:07 INF] Collecting docker logs for redis_3a1d29cb-6.
[19:49:07 INF] Running docker command network connect tye_network_8c0faa56-4 graphapi-dapr-proxy_aa1a07ae-1 --alias graphapi-dapr
[19:49:08 INF] Running container productcatalogapi-dapr-proxy_b75974b4-0 with ID 146999f9017d
[19:49:08 INF] Running docker command network connect tye_network_8c0faa56-4 productcatalogapi-dapr-proxy_b75974b4-0 --alias productcatalogapi-dapr
[19:49:08 INF] Running container identityserver-dapr-proxy_60c7074b-c with ID 808bb53cf5fc
[19:49:08 INF] Running docker command network connect tye_network_8c0faa56-4 identityserver-dapr-proxy_60c7074b-c --alias identityserver-dapr
[19:49:08 INF] Collecting docker logs for inventoryapi-proxy_2b78b28c-0.
[19:49:08 INF] Collecting docker logs for webuihost-proxy_cd947ec2-4.
[19:49:08 INF] Collecting docker logs for graphapi-dapr-proxy_aa1a07ae-1.
[19:49:08 INF] Running container webuihost-dapr-proxy_26ac3bed-f with ID 8524ead66529
[19:49:08 INF] Running docker command network connect tye_network_8c0faa56-4 webuihost-dapr-proxy_26ac3bed-f --alias webuihost-dapr
[19:49:08 INF] Running container inventoryapi-dapr-proxy_a1fcccbb-5 with ID 783bd0cc59c5
[19:49:08 INF] Running docker command network connect tye_network_8c0faa56-4 inventoryapi-dapr-proxy_a1fcccbb-5 --alias inventoryapi-dapr
[19:49:08 INF] Collecting docker logs for productcatalogapi-dapr-proxy_b75974b4-0.
[19:49:09 INF] Collecting docker logs for identityserver-dapr-proxy_60c7074b-c.
[19:49:09 INF] Collecting docker logs for webuihost-dapr-proxy_26ac3bed-f.
[19:49:09 INF] Collecting docker logs for inventoryapi-dapr-proxy_a1fcccbb-5.
[19:49:26 INF] docker logs collection for sqlserver_98aff541-2 complete with exit code 0
[19:49:26 INF] Stopping container sqlserver_98aff541-2 with ID 163fda6e3456
[19:49:26 INF] docker logs collection for redis_3a1d29cb-6 complete with exit code 0
[19:49:26 INF] docker logs collection for graphapi-proxy_412bbd63-a complete with exit code 0
[19:49:26 INF] Stopping container redis_3a1d29cb-6 with ID fe033e1ddc0c
[19:49:26 INF] docker logs collection for webuihost-proxy_cd947ec2-4 complete with exit code 0
[19:49:26 INF] docker logs collection for graphapi-dapr-proxy_aa1a07ae-1 complete with exit code 0
[19:49:26 INF] docker logs collection for identityserver-dapr-proxy_60c7074b-c complete with exit code 0
[19:49:26 INF] docker logs collection for productcatalogapi-proxy_11e14a58-6 complete with exit code 0
[19:49:26 INF] docker logs collection for identityserver-proxy_e3751a17-f complete with exit code 0
[19:49:26 INF] Stopping container identityserver-proxy_e3751a17-f with ID 6a735b92d82c
[19:49:26 INF] Stopping container graphapi-proxy_412bbd63-a with ID 9c43b9bc009f
[19:49:26 INF] Stopping container webuihost-proxy_cd947ec2-4 with ID 0240970bf67e
[19:49:26 INF] Stopping container graphapi-dapr-proxy_aa1a07ae-1 with ID 11e4ce241c7f
[19:49:26 INF] Stopping container identityserver-dapr-proxy_60c7074b-c with ID 808bb53cf5fc
[19:49:26 INF] docker logs collection for productcatalogapi-dapr-proxy_b75974b4-0 complete with exit code 0
[19:49:26 INF] Stopping container productcatalogapi-proxy_11e14a58-6 with ID 10c17a97090a
[19:49:26 INF] docker logs collection for inventoryapi-proxy_2b78b28c-0 complete with exit code 0
[19:49:26 INF] docker logs collection for inventoryapi-dapr-proxy_a1fcccbb-5 complete with exit code 0
[19:49:26 INF] docker logs collection for webuihost-dapr-proxy_26ac3bed-f complete with exit code 0
[19:49:26 INF] Stopping container productcatalogapi-dapr-proxy_b75974b4-0 with ID 146999f9017d
[19:49:26 INF] Stopping container inventoryapi-proxy_2b78b28c-0 with ID e09ede1a1c17
[19:49:26 INF] Stopping container inventoryapi-dapr-proxy_a1fcccbb-5 with ID 783bd0cc59c5
[19:49:26 INF] Stopping container webuihost-dapr-proxy_26ac3bed-f with ID 8524ead66529
[19:49:28 INF] Stopped container redis_3a1d29cb-6 with ID fe033e1ddc0c exited with 0
[19:49:28 INF] Stopped container webuihost-proxy_cd947ec2-4 with ID 0240970bf67e exited with 0
[19:49:28 INF] Removed container redis_3a1d29cb-6 with ID fe033e1ddc0c exited with 0
[19:49:28 INF] Stopped container graphapi-proxy_412bbd63-a with ID 9c43b9bc009f exited with 0
[19:49:28 INF] Removed container webuihost-proxy_cd947ec2-4 with ID 0240970bf67e exited with 0
[19:49:29 INF] Removed container graphapi-proxy_412bbd63-a with ID 9c43b9bc009f exited with 0
[19:49:29 INF] Stopped container identityserver-proxy_e3751a17-f with ID 6a735b92d82c exited with 0
[19:49:29 INF] Stopped container inventoryapi-proxy_2b78b28c-0 with ID e09ede1a1c17 exited with 0
[19:49:29 INF] Stopped container identityserver-dapr-proxy_60c7074b-c with ID 808bb53cf5fc exited with 0
[19:49:29 INF] Stopped container productcatalogapi-dapr-proxy_b75974b4-0 with ID 146999f9017d exited with 0
[19:49:29 INF] Removed container identityserver-proxy_e3751a17-f with ID 6a735b92d82c exited with 0
[19:49:29 INF] Stopped container productcatalogapi-proxy_11e14a58-6 with ID 10c17a97090a exited with 0
[19:49:29 INF] Removed container inventoryapi-proxy_2b78b28c-0 with ID e09ede1a1c17 exited with 0
[19:49:29 INF] Removed container identityserver-dapr-proxy_60c7074b-c with ID 808bb53cf5fc exited with 0
[19:49:29 INF] Stopped container inventoryapi-dapr-proxy_a1fcccbb-5 with ID 783bd0cc59c5 exited with 0
[19:49:29 INF] Removed container productcatalogapi-dapr-proxy_b75974b4-0 with ID 146999f9017d exited with 0
[19:49:29 INF] Stopped container webuihost-dapr-proxy_26ac3bed-f with ID 8524ead66529 exited with 0
[19:49:29 INF] Removed container productcatalogapi-proxy_11e14a58-6 with ID 10c17a97090a exited with 0
[19:49:29 INF] Stopped container graphapi-dapr-proxy_aa1a07ae-1 with ID 11e4ce241c7f exited with 0
[19:49:29 INF] Removed container inventoryapi-dapr-proxy_a1fcccbb-5 with ID 783bd0cc59c5 exited with 0
[19:49:29 INF] Stopped container sqlserver_98aff541-2 with ID 163fda6e3456 exited with 0
[19:49:29 INF] Removed container webuihost-dapr-proxy_26ac3bed-f with ID 8524ead66529 exited with 0
[19:49:29 INF] Removed container graphapi-dapr-proxy_aa1a07ae-1 with ID 11e4ce241c7f exited with 0
[19:49:30 INF] Removed container sqlserver_98aff541-2 with ID 163fda6e3456 exited with 0
[19:49:30 INF] Removing docker network tye_network_8c0faa56-4
[19:49:30 INF] Running docker command network rm tye_network_8c0faa56-4
[19:49:30 ERR] Error while shutting down
System.InvalidOperationException: Could not find binding 'grpc' for service 'graphapi-dapr'.
   at Microsoft.Tye.Hosting.Model.Application.<PopulateEnvironment>g__GetValueFromBinding|17_0(List`1 bindings, EnvironmentVariableSource source) in /_/src/Microsoft.Tye.Hosting/Model/Application.cs:line 66
   at Microsoft.Tye.Hosting.Model.Application.PopulateEnvironment(Service service, Action`2 set, String defaultHost) in /_/src/Microsoft.Tye.Hosting/Model/Application.cs:line 47
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 298
```

### Further technical details

- tye tool: `0.3.0-alpha.20265.1+ef441e87047930e04d24646e0d89183b07552747`
- dapr CLI: `0.7.0`
- dapr runtime: `0.7.0`
- OS: Windows 10
- Source code: https://github.com/thangchung/practical-dapr/blob/feature%2Fupgrade-tye-0.3/tye.yaml

**Comment by KaiWalter** [comment]
same problem here - also with my stripped down version of a Dapr setup : https://github.com/KaiWalter/dapr-experimental/tree/v0.1/app2app

Replica is detected for the `redis` container but not for the `app` and `app-dapr` containers.

OS and Dapr CLI/RT version are identical.

**Comment by KaiWalter** [comment]
I suspect that streaming logs is not working in the WSL2 / Docker Desktop combo we use: https://github.com/dotnet/tye/blob/65c09d737e36edd3757b248967db252a7fff9e75/src/Microsoft.Tye.Hosting/DockerRunner.cs#L303

**Comment by KaiWalter** [comment]
It seems that by adding the Dapr proxies in the line below, the `Service` object of the `proxy` is receiving the replica information and logs: https://github.com/dotnet/tye/blob/65c09d737e36edd3757b248967db252a7fff9e75/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L74 

When applying a dirty hack and adding the proxies replicas to the replicas which are queried by the dashboard, replica information and logs become available. https://github.com/dotnet/tye/blob/65c09d737e36edd3757b248967db252a7fff9e75/src/Microsoft.Tye.Hosting/DockerRunner.cs#L150 

```C#
            Dictionary<string, Service> dummyServices = new Dictionary<string, Service>();

            foreach (var s in containers)
            {
                var docker = (DockerRunInfo)s.Description.RunInfo!;

                tasks[index++] = StartContainerAsync(application, s, docker, dockerNetwork);

                foreach(var sa in application.Services)
                {
                    if(s.Description.Name == sa.Key + "-proxy")
                    {
                        _logger.LogInformation($"{s.Description.Name} {s.Replicas.Count}");
                        foreach(var r in s.Replicas)
                        {
                            dummyServices.Add(s.Description.Name, r.Value.Service);
                        }
                        _logger.LogInformation($"{sa.Key} {sa.Value.Replicas.Count}");
                    }
                }

            }

            foreach(var ds in dummyServices)
            {
                application.Services.Add(ds.Key, ds.Value);
            }

            await Task.WhenAll(tasks);
```

**Comment by jkotalik** [comment]
I found the root issue, took quite a while to figure out. Once the PR referenced is merged, this should be fixed in the latest nightlys.

**Comment by jkotalik** [comment]
Fix merged, would really appreciate you all trying the latest nightly builds to verify the fix works ❤️

**Comment by thangchung** [comment]
@jkotalik It works now. Lovely 👍
