### ISSUE TITLE
Unable to connect to MySQL from API project using Tye

### ISSUE THREAD

**Issue by Matthiee** [dotnet/tye#503]
### Describe the bug
I tried to convert my docker-compose to tye and ran into an issue where the backend api is unable to connect to mysql service, but it is able to connect to redis service. 

When running `docker-compose up` everything works fine. 
When running `tye run` the backend fails to connect to mysql. 

Check logs for api or navigate to `/api/products`

### To Reproduce
I have a repo here: https://github.com/Matthiee/NgDockerComposeTest/tree/tye/DockerTest

Contains both the working `docker-compose.yml` and the converted `tye.yml`

Stacktrace:
```
[api_1ba45eef-f]:D:\Source\Repos\NgDockerComposeTest\DockerTest\API\bin\Debug\netcoreapp3.1\API.exe
[api_1ba45eef-f]: info: API.Program[0]
[api_1ba45eef-f]: Db connection string: Server=localhost;Port=3306;Database=dockertest;Uid=dockeruser;Pwd=password;
[api_1ba45eef-f]: info: API.Program[0]
[api_1ba45eef-f]: Migrating database..
[api_1ba45eef-f]: fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
[api_1ba45eef-f]: An error occurred using the connection to database '' on server 'localhost'.
[api_1ba45eef-f]: fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
[api_1ba45eef-f]: An error occurred using the connection to database '' on server 'localhost'.
[api_1ba45eef-f]: fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
[api_1ba45eef-f]: An error occurred using the connection to database '' on server 'localhost'.
[api_1ba45eef-f]: fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
[api_1ba45eef-f]: An error occurred using the connection to database '' on server 'localhost'.
[api_1ba45eef-f]: fail: API.Program[0]
[api_1ba45eef-f]: An error occured during migration
[api_1ba45eef-f]: MySql.Data.MySqlClient.MySqlException (0x80004005): Host '172.17.0.1' is not allowed to connect to this MySQL server
[api_1ba45eef-f]: at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 774
[api_1ba45eef-f]: at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 354
[api_1ba45eef-f]: at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 657
[api_1ba45eef-f]: at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
[api_1ba45eef-f]: at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
[api_1ba45eef-f]: at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
[api_1ba45eef-f]: --- End of stack trace from previous location where exception was thrown ---
[api_1ba45eef-f]: at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
[api_1ba45eef-f]: --- End of stack trace from previous location where exception was thrown ---
[api_1ba45eef-f]: at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
[api_1ba45eef-f]: --- End of stack trace from previous location where exception was thrown ---
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
[api_1ba45eef-f]: at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
[api_1ba45eef-f]: at API.Program.Main(String[] args) in D:\Source\Repos\NgDockerComposeTest\DockerTest\API\Program.cs:line 33
[api_1ba45eef-f]: info: API.Program[0]
[api_1ba45eef-f]: Running application..
[api_1ba45eef-f]: info: Microsoft.Hosting.Lifetime[0]
[api_1ba45eef-f]: Now listening on: http://localhost:9404
[api_1ba45eef-f]: info: Microsoft.Hosting.Lifetime[0]
[api_1ba45eef-f]: Now listening on: https://localhost:9405
[api_1ba45eef-f]: info: Microsoft.Hosting.Lifetime[0]
[api_1ba45eef-f]: Application started. Press Ctrl+C to shut down.
```

### Further technical details

```
❯ tye --version
0.2.0-alpha.20258.3+bf3bc0913b37e77f5f3ef14f409b3feb794cc447
```

```
❯ [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

**Comment by rynowak** [comment]
I tried out your repo and I saw this error on the first run. It looks like the issue with connection is transient (your app starting faster than the database). I suspect that what you're seeing is similar - a timing issue. **If you're seeing a persistent failure to connect then let us know and we'll try to help further.**

Tye doesn't currently have a feature like docker-compose' `dependencies`. Dependencies in docker-compose includes configuring startup order. Tye starts all of your services together without order. This causes problems in the case that you're trying to have an application access a data source on initialization (like seeding).

In general having an app self-seed/migrate the database on init isn't something you can get away with in production for a real distributed app because of the problems it introduces with rollbacks, versioning, replicas, startup order, etc. I think the team is thinking about how to address this in a more first-class way.

@glennc - counter_of_need_for_seeding++

**Comment by Matthiee** [comment]
I agree the API starts up before the DB. But still ignoring the migration failure and navigating to `/api/products` causes `MySql.Data.MySqlClient.MySqlException (0x80004005): Host '172.17.0.1' is not allowed to connect to this MySQL server`

-- 

So I tried to run my repo on my laptop and there it works fine. 

-- 

On my development machine I do have MySQL installed locally (services disabled), perhaps this is causing some issues..

**Comment by rynowak** [comment]
If you look at the logs (via Tye dashboard and the console) do you see logs for the mysql? or is it failing to start due to port conflict? Does it show `1/1` running or `0/1`?

It's possible that the container is failing to start if the port is in use, and then you get an error connecting to the already running instance. 

Another thing I found from doing a quick check is that MySQL limits each username to a set of IP addresses, with various solutions. I'm not sure why this would be different for you on different machines. Are you having success on a particular OS and failure on a different OS?

**Comment by jkotalik** [comment]
I think we were considering having dependencies for services, specifically for the scenario where you have databases you want to have started first. However, I'm still hesitant due to how this will be checked for deployment scenarios. Do we check that a secret is set before deploying?

**Comment by Matthiee** [comment]
@rynowak All services show `1/1` and no port conflicts in the logs. 

So I've spent some time trying to get this to work.. 

- Changed the port of my local MySQL installation (just to be sure)
- Checked `netstat -a -n -o` that no other process is using port `3306`

But the API still returns `MySql.Data.MySqlClient.MySqlException (0x80004005): Host '172.17.0.1' is not allowed to connect to this MySQL server` on this one device. (Still working on my other laptop).

I switched DB providers to latest MS SQL docker image and latest MySQL docker image both worked out of the box no conflicts or problems.

**Comment by rynowak** [comment]
So what's different between your docker-compose case and Tye is where the connection *comes from*. That's the hint that the error message gives you - `Host '172.17.0.1' is not allowed to connect to this MySQL server`. 

`172.17.0.1` is the IP address used by docker for the host gateway - meaning that the connection is coming from the host machine, rather than another container on the same network. In docker-compose your application is running in another container - with Tye it's running on your host (your host OS, not in a container). 

Can you try adding the following to `env` for the mysql container:

```yaml
- name: MYSQL_ROOT_HOST
   value: '%'
```

If the docs are to be believed this allows connections from any IP.
