### ISSUE TITLE
[SILENT ERROR] Tye run does not supports for CsProj containing "TargetFrameworkS"

### ISSUE THREAD

**Issue by tebeco** [dotnet/tye#564]
### Describe the bug
If you are trying to do `tye run` and one of the `xxproj`  is using `TargetFrameworks` it will silently crash on restore/build
And `tye run` output an error about a "Missing file"
Few issue here:
* We might want to know the name of the file missing
* We might want to know that the `dotnet xxx /t:....` failed ==> [Cannot find Target ResolveReferences](https://github.com/dotnet/tye/blob/e368d04e914a3880a1a10e21cf5c271966241dbd/src/Microsoft.Tye.Core/ProjectReader.cs#L208-L218)
* We might want to be able to do `tye run --framework netcoreapp3.1` (see investigation)
* We might want to be able to do in `tye.yaml`
```yaml
name: THE_NAME
services:
- name: THE_SERVICE
  project: src/THE_SERVICE/THE_SERVICE.csproj
  framework: netcoreapp3.1
```

### To Reproduce
DISCLAMER:
I did all the investigation on a CORP project, so i'm not entierlly sure this repro is enought
Naive repro:
* `dotnet new webapi`
* replace `TargetFramework` by `TargetFrameworks`
* `tye init`
* `tye run`

### Further technical details
- Include the output of `tye --version`
```
[12:24]❯ tye --version
0.3.0-alpha.20318.3+224101f108311b4d38b226eed75d0ec03fa14db1
```
- The platform: `Windows`

If the repro is not enought, I believe that this one might be very similar to CORP repo:
```
mkdir repro
cd repro
git clone https://github.com/dotnet-experimentations/CentrallyManagingNuGetPackageVersions/
cd CentrallyManagingNuGetPackageVersions
cd WithMsBuild   # <==== THIS IS IMPORTANT :D
tye init
tye run
```

```
[12:23:23 INF] Executing application from C:\dev\xxxxxxx\tye.yaml
[12:23:23 INF] Dashboard running on http://127.0.0.1:8000
[12:23:23 INF] Building projects
[12:23:42 INF] Launching service XXXXXXXXXXXXXXXXXX-aspnetcore_f992c4c5-d:
[12:23:42 INF] Launching service YYYYYYYYYYYYYYYYY_5a5c648c-6:
[12:23:42 ERR] Failed to launch process for service XXXXXXXXXXXXXXXXXX-aspnetcore_f992c4c5-d
System.InvalidOperationException: Cannot start process because a file name has not been provided.  <============= This is very missleading
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 105
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 319
```
![image](https://user-images.githubusercontent.com/2266487/85847722-37fdf380-b7a8-11ea-9efd-350d5004f83a.png)

I managed to get more info running `tye run -v Debug` 
```
    Assets file has not changed. Skipping assets file writing. Path: C:\dev\XXXXXXXXXXXXX\obj\project.assets.json
    Writing packages lock file at disk. Path: C:\dev\XXXXXXXXXXXXX\packages.lock.json
    Restored C:\dev\XXXXXXXXXXXXX\XXXXXXXXXXXXX.csproj (in 5.12 sec).
    Restored C:\dev\XXXXXXXXXXXXX\XXXXXXXXXXXXX.csproj (in 4.28 sec).

    NuGet Config files used:
        C:\dev\XXXXXXXXXXXXX\Users\USER_NAME\AppData\Roaming\NuGet\NuGet.Config
        C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

    Feeds used:
        https://FEED_ONE/
        https://FEED_TWO/
        https://FEED_THREE/

    Installed:
        4 package(s) to C:\dev\path\to\each\file.csproj
        4 package(s) to C:\dev\path\to\each\file.csproj
        4 package(s) to C:\dev\path\to\each\file.csproj
        56 package(s) to C:\dev\path\to\each\file.csproj
        19 package(s) to C:\dev\path\to\each\file.csproj
        114 package(s) to C:\dev\path\to\each\file.csproj
        94 package(s) to C:\dev\path\to\each\file.csproj
        151 package(s) to C:\dev\path\to\each\file.csproj
        141 package(s) to C:\dev\path\to\each\file.csproj
        143 package(s) to C:\dev\path\to\each\file.csproj
        238 package(s) to C:\dev\path\to\each\file.csproj
        242 package(s) to C:\dev\path\to\each\file.csproj
        354 package(s) to C:\dev\path\to\each\file.csproj
        410 package(s) to C:\dev\path\to\each\file.csproj
        158 package(s) to C:\dev\path\to\each\file.csproj
        204 package(s) to C:\dev\path\to\each\file.csproj
    3 of 19 projects are up-to-date for restore.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:05.62
Restored project 'C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj'.
Build started 6/26/2020 11:33:37.
__________________________________________________
Project "C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):

C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj : error MSB4057: The target "ResolveReferences" does not exist in the project.

Done building project "MY_PROJECT.csproj" -- FAILED.

Build FAILED.

C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj : error MSB4057: The target "ResolveReferences" does not exist in the project.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.00
Found application version: 1.0.0
RunCommand=
RunArguments=
TargetPath=
PublishDir=
AssemblyName=MY_PROJECT
IntermediateOutputPath=obj\Debug\
Found target framework:
Found shared frameworks:
IsAspNet=True
Evaluation Took: 126340.9333ms
Launching Tye Host...

[11:33:38 INF] Executing application from C:\dev\XXXXXXXXXXXXX:38 INF] Dashboard running on http://127.0.0.1:8000
[11:33:38 INF] Building projects
[11:33:54 INF] Launching service MY_PROJECT_c366d90a-f:
[11:33:54 ERR] Failed to launch process for service MY_PROJECT_c366d90a-f
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 105
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 319
```

The interesting part is this one I think :
```
Project "C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):

C:\dev\XXXXXXXXXXXXX.HubApp\MY_PROJECT.csproj : error MSB4057: The target "ResolveReferences" does not exist in the project.
```

so I found this in `dotnet tye` code :
https://github.com/dotnet/tye/blob/e368d04e914a3880a1a10e21cf5c271966241dbd/src/Microsoft.Tye.Core/ProjectReader.cs#L208-L218

I managed to reproduce a low level error by running:
```
dotnet msbuild "C:\dev\XXXXX\Y.csproj" /t:ResolveReferences /t:ResolvePackageDependenciesDesignTime /t:PrepareResources /t:GetAssemblyAttributes
```

I looked a bit around this error and this seems to be related sometimes to the error you have when running `dotnet run` on an `sln` rather than a `csproj`. In this case I did try both `dotnet run` and `dotnet run --project path/to/csproj`
Which did not worked for an obvious reason:
![image](https://user-images.githubusercontent.com/2266487/85853515-ef980300-b7b2-11ea-8d9b-b4e331e3f92e.png)

This works as expected:
`dotnet run --framework netcoreapp3.1` 

As I could not find `tye run --framework netcoreapp3.1` (maybe there's a flag in the YAML ?) I changed the `csproj` from :  
```
<TargetFramworks>$(SrcTargetFrameworks)</TargetFramworks>
```
To:
```
<TargetFramwork>$(SrcTargetFrameworks)</TargetFramwork>
```
===> That finally works <=== even though it's not really a "goal" as a consumer :)
having a `--framework` from the CLI for `tye run` 
then rolledback to `TargetFramworks` and I tried to edit the `tye.yaml` from
```yaml
name: foobar
services:
- name: foo
  project: src/foo/foo.csproj
```
to
```yaml
name: foobar
services:
- name: foo
  project: src/foo/foo.csproj
  framework: netcoreapp3.1
```
![image](https://user-images.githubusercontent.com/2266487/85855371-76021400-b7b6-11ea-8dad-8d026ec21225.png)

**Comment by tebeco** [comment]
also see #608
