### ISSUE TITLE
Bad error on windows if docker is not running

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#57]
```txt
            error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=.dockerfile.058f67bf52a9aa2d7818&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=nd26yagsci7i5sducobirn5yd&shmsize=0&t=rynowak%2Fbackend%3A0.1.28-alpha.g9bd368b4a1&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
An unhandled exception has occurred, how unseemly:
Tye.CommandException: 'docker build' failed.
   at Tye.DockerContainerBuilder.BuildContainerImageAsync(OutputContext output, Application application, ServiceEntry service, Project project, ContainerInfo container) in C:\git\dotnet\tye\src\Tye.Core\DockerContainerBuilder.cs:line 67       at Tye.BuildDockerImageStep.ExecuteAsync(OutputContext output, Application application, ServiceEntry service) in C:\git\dotnet\tye\src\Tye.Core\BuildDockerImageStep.cs:line 28
   at Tye.ServiceExecutor.ExecuteAsync(ServiceEntry service) in C:\git\dotnet\tye\src\Tye.Core\ServiceExecutor.cs:line 46
   at Tye.Program.ExecuteGenerateAsync(OutputContext output, ConfigApplication application, String environment, Boolean interactive) in C:\git\dotnet\tye\src\tye\Program.GenerateCommand.cs:line 56
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()    --- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by davidfowl** [comment]
@rynowak This is done right?
