### ISSUE TITLE
Ingress to external service

### ISSUE THREAD

**Issue by brunoblank** [dotnet/tye#622]
### Describe the bug
We run our web app using a spa frontend and web-api backend in kubernetes with ingress:
``` 
    /    => spa
    /api => api
```
When trying to set this scenario up using tye it is not possible to serve the spa (as it is not a dotnet service) we run it separately as a `yarn serve` in a separate window.

There is an exception when referencing the extarnal using an ingress rule.
```
name: tye
ingress:
  - name: ingress
    bindings:
      - port: 6002
    rules:
      - path: /api
        service: backend
      - path: /
        service: spa
services:
- name: backend
  project: "backend/backend.csproj"
- name: spa
  external: true
  bindings:
  - protocol: http
    host: localhost
    port: 55555
```

### To Reproduce
* Create a default webapi project `dotnet new webapi -n backend`
* use the yaml above as `tye.yaml`
* run `tye run`

Exception:
```
An unhandled exception has occurred, how unseemly:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Microsoft.Tye.Hosting.HttpProxyService.StartAsync(Application application)
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StartAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 24
   at Microsoft.Tye.Hosting.TyeHost.StartAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 96
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 60
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 70
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__10_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__10_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Further technical details

- Include the output of `tye --version`
**0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243**

- The platform (Linux/macOS/Windows)
**Windows**

**Comment by brunoblank** [comment]
ping

@rynowak any thoughts or comments regarding this way of using ingress?

**Comment by jongio** [comment]
Related with suggestion for External https://github.com/dotnet/tye/issues/749
