### ISSUE TITLE
tye run with net50

### ISSUE THREAD

**Issue by i-love-code** [dotnet/tye#670]
Just curious, is this supposed to work with .NET 5 RC1? It looks like some things work, some do not.

Example: `tye run --watch`

Running `tye run --watch` with two .NET 5 RC1 web projects (referencing a handful of netstandard2.1 libraries, if it matters)

### To Reproduce

versions
```
λ  tye --version
0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243

λ  dotnet --version
5.0.100-rc.1.20452.10
```

tye.yaml
```
name: ProjectName

services:
- name: ProjectName-web-marketing
  project: src/ProjectName.Web.Marketing/ProjectName.Web.Marketing.csproj
  bindings:
  - port: 5000
    protocol: https
  
- name: ProjectName-web-backend
  project: src/ProjectName.Web.Backend/ProjectName.Web.Backend.csproj
  bindings:
    - port: 5050
      protocol: https
```

The console output:
```
λ  tye run -v debug --watch
Loading Application Details...
Locating .NET SDK...
Found .NET SDK at: C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\
Registered .NET SDK.Loading project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj'.
Loaded project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj'.
Restoring project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj'.
Build started 9/21/2020 1:16:42 AM.
__________________________________________________
Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj" (Restore target(s)):

Target _FilterRestoreGraphProjectInputItems:
    D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj : warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(26,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(28,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(30,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(32,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    __________________________________________________
    Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj" is building "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj" (_IsProjectRestoreSupported target(s)):

  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(309,5): error MSB4062: The "NuGet.Build.Tasks.WarnForInvalidProjectsTask" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building target "_FilterRestoreGraphProjectInputItems" in project "ProjectName.Web.Marketing.csproj" -- FAILED.

Done building project "ProjectName.Web.Marketing.csproj" -- FAILED.

Build FAILED.

D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj : warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(26,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(28,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(30,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(32,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(309,5): error MSB4062: The "NuGet.Build.Tasks.WarnForInvalidProjectsTask" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    6 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.31
Restored project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj'.
Build started 9/21/2020 1:16:42 AM.
__________________________________________________
Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):

Target ProcessFrameworkReferences:
  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(39,5): error MSB4062: The "CheckForDuplicateFrameworkReferences" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\..\tools\net5.0/Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building target "ProcessFrameworkReferences" in project "ProjectName.Web.Marketing.csproj" -- FAILED.

Done building project "ProjectName.Web.Marketing.csproj" -- FAILED.

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(39,5): error MSB4062: The "CheckForDuplicateFrameworkReferences" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\..\tools\net5.0/Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.00
Found application version: 1.0.0
RunCommand=D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\bin\Debug\net5.0\ProjectName.Web.Marketing.exe
RunArguments=
TargetPath=D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\bin\Debug\net5.0\ProjectName.Web.Marketing.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=ProjectName.Web.Marketing
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1080.4724ms
Loading project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj'.
Loaded project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj'.
Restoring project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj'.
Build started 9/21/2020 1:16:42 AM.
__________________________________________________
Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj" (Restore target(s)):

Target _FilterRestoreGraphProjectInputItems:
    D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj : warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(26,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(28,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(30,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(32,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    __________________________________________________
    Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj" is building "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj" (_IsProjectRestoreSupported target(s)):

  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(309,5): error MSB4062: The "NuGet.Build.Tasks.WarnForInvalidProjectsTask" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building target "_FilterRestoreGraphProjectInputItems" in project "ProjectName.Web.Backend.csproj" -- FAILED.

Done building project "ProjectName.Web.Backend.csproj" -- FAILED.

Build FAILED.

D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj : warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(26,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(28,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(30,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(32,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(309,5): error MSB4062: The "NuGet.Build.Tasks.WarnForInvalidProjectsTask" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    6 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.04
Restored project 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj'.
Build started 9/21/2020 1:16:42 AM.
__________________________________________________
Project "D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):

Target ProcessFrameworkReferences:
  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(39,5): error MSB4062: The "CheckForDuplicateFrameworkReferences" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\..\tools\net5.0/Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building target "ProcessFrameworkReferences" in project "ProjectName.Web.Backend.csproj" -- FAILED.

Done building project "ProjectName.Web.Backend.csproj" -- FAILED.

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(39,5): error MSB4062: The "CheckForDuplicateFrameworkReferences" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\..\tools\net5.0/Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.00
Found application version: 1.0.0
RunCommand=D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\bin\Debug\net5.0\ProjectName.Web.Backend.exe
RunArguments=
TargetPath=D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\bin\Debug\net5.0\ProjectName.Web.Backend.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=ProjectName.Web.Backend
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 303.5642ms
Injecting seq service...
Launching Tye Host...

[01:16:42 INF] Executing application from D:\Git\GitUsername\ProjectName\tye.yaml
[01:16:43 INF] logs: Using Seq at http://localhost:5341
[01:16:43 INF] Dashboard running on http://127.0.0.1:8000
[01:16:43 INF] Docker image datalust/seq already installed
[01:16:43 INF] Creating docker network tye_network_1baf01a5-9
[01:16:43 INF] Running docker command network create --driver bridge tye_network_1baf01a5-9
[01:16:44 INF] Running image datalust/seq for seq_2df565ea-a
[01:16:44 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for ProjectName-web-marketing-proxy_4b3586d6-8
[01:16:44 INF] Running image mcr.microsoft.com/dotnet/core/sdk:3.1 for ProjectName-web-backend-proxy_d2730460-9
[01:16:44 INF] Building projects
[01:16:44 INF] Running container seq_2df565ea-a with ID 81f313fe47c1
[01:16:44 INF] Running docker command network connect tye_network_1baf01a5-9 seq_2df565ea-a --alias seq
[01:16:45 INF] Replica seq_2df565ea-a is moving to a ready state
[01:16:45 INF] Collecting docker logs for seq_2df565ea-a.
[01:16:45 INF] Launching service ProjectName-web-marketing_ac6c8183-8: D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\bin\Debug\net5.0\ProjectName.Web.Marketing.exe
[01:16:45 INF] Launching service ProjectName-web-backend_4cc76848-e: D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\bin\Debug\net5.0\ProjectName.Web.Backend.exe
[01:16:45 DBG] Running MSBuild target 'GenerateWatchList' on 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj'
[01:16:45 DBG] Running MSBuild target 'GenerateWatchList' on 'D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj'
[01:16:46 ERR] Failed to launch process for service ProjectName-web-marketing_ac6c8183-8
System.InvalidOperationException: Command dotnet msbuild D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Marketing\ProjectName.Web.Marketing.csproj /p:_DotNetWatchListFile=C:\Users\MyWindowsUsername\AppData\Local\Temp\3dnkvo4w.q0i /nologo /v:n /t:GenerateWatchList /p:DotNetWatchBuild=true /p:DesignTimeBuild=true /p:CustomAfterMicrosoftCommonTargets=C:\Users\MyWindowsUsername\.dotnet\tools\.store\microsoft.tye\0.4.0-alpha.20371.1\microsoft.tye\0.4.0-alpha.20371.1\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets /p:CustomAfterMicrosoftCommonCrossTargetingTargets=C:\Users\MyWindowsUsername\.dotnet\tools\.store\microsoft.tye\0.4.0-alpha.20371.1\microsoft.tye\0.4.0-alpha.20371.1\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets returned exit code 1
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 140
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory.CreateAsync(CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs:line 73
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, String replica, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs:line 42
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 385
[01:16:46 ERR] Failed to launch process for service ProjectName-web-backend_4cc76848-e
System.InvalidOperationException: Command dotnet msbuild D:\Git\GitUsername\ProjectName\src\ProjectName.Web.Backend\ProjectName.Web.Backend.csproj /p:_DotNetWatchListFile=C:\Users\MyWindowsUsername\AppData\Local\Temp\vfpfnnok.oee /nologo /v:n /t:GenerateWatchList /p:DotNetWatchBuild=true /p:DesignTimeBuild=true /p:CustomAfterMicrosoftCommonTargets=C:\Users\MyWindowsUsername\.dotnet\tools\.store\microsoft.tye\0.4.0-alpha.20371.1\microsoft.tye\0.4.0-alpha.20371.1\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets /p:CustomAfterMicrosoftCommonCrossTargetingTargets=C:\Users\MyWindowsUsername\.dotnet\tools\.store\microsoft.tye\0.4.0-alpha.20371.1\microsoft.tye\0.4.0-alpha.20371.1\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets returned exit code 1
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 140
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory.CreateAsync(CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs:line 73
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, String replica, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs:line 42
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 385
[01:16:47 INF] Tye Host is stopping...
[01:16:47 INF] docker logs collection for seq_2df565ea-a complete with exit code 0
[01:16:47 ERR] docker run failed for ProjectName-web-marketing-proxy with exit code -1:
[01:16:47 ERR] docker run failed for ProjectName-web-backend-proxy with exit code -1:
[01:16:47 INF] Stopping container seq_2df565ea-a with ID 81f313fe47c1
[01:16:53 INF] Stopped container seq_2df565ea-a with ID 81f313fe47c1 exited with 0
[01:16:53 INF] Removed container seq_2df565ea-a with ID 81f313fe47c1 exited with 0
[01:16:53 INF] Removing docker network tye_network_1baf01a5-9
[01:16:53 INF] Running docker command network rm tye_network_1baf01a5-9
```

### Further technical details

Platform: Windows (10 x64)

**Comment by i-love-code** [comment]
Add'l info, just in case:

- Tye starts and runs these just fine without the `--watch` command
- The projects all run fine normally, via `dotnet run` and `dotnet watch --project <..> run`
- I don't get the warnings/errors above when building/running projects individually

**Comment by GeorgeS2019** [comment]
I so far only manage to get tye work in WSL2

tye --version
0.5.0-alpha.20515.1+869433786bd9b0432435fa86906ce1fe714f9751


I have problem getting it installed in Win10 Pro.
