### ISSUE TITLE
System.InvalidOperationException: Cannot start process because a file name has not been provided.

### ISSUE THREAD

**Issue by Ganesh-Sattawan** [dotnet/tye#692]
I am trying to run an azure function which is in App folder of solution and getting below error 
YML File configuration:
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: service1
services:
- name: demo-service1
  project: App/service1.csproj

Error:
[11:15:01 INF] Executing application from C:\Services\Service1\tye.yaml
[11:15:02 INF] Dashboard running on http://127.0.0.1:8000
[11:15:02 INF] Building projects
[11:15:32 INF] Launching service service1_885101bb-7:
[11:15:32 ERR] Failed to launch process for service fireservice1_885101bb-7
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 106
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
[11:15:42 INF] Launching service service1_db50b321-7:
[11:15:43 ERR] Failed to launch process for service service1_db50b321-7
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 106
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
[11:16:03 INF] Launching service service1_21bbcb4d-d:
[11:16:03 ERR] Failed to launch process for service service1_21bbcb4d-d
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 106
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
[11:16:43 INF] Launching service service1_acaf992e-d:
[11:16:43 ERR] Failed to launch process for service service1_acaf992e-d
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 106
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402

**Comment by tebeco** [comment]
hello,

I can't be sure about your issue but last time i got this error:

> InvalidOperationException: Cannot start process because a file name has not been provided.

it was because the project could not either build or run.

eg: using multiple target framework without specifying which one it should use to run

this could be a different root cause but this is how i understand the error : "no build => nothing on disk create to be ran"

**Comment by Ganesh-Sattawan** [comment]
> hello,
> 
> I can't be sure about your issue but last time i got this error:
> 
> > InvalidOperationException: Cannot start process because a file name has not been provided.
> 
> it was because the project could not either build or run.
> 
> eg: using multiple target framework without specifying which one it should use to run
> 
> this could be a different root cause but this is how i understand the error : "no build => nothing on disk create to be ran"

without tye Project is building and running , however not working with tye, single target framework dot net core 3.1.

**Comment by tebeco** [comment]
> without tye Project is building and running , however not working with tye

yep dotnet/tye copy the project and redo the restore / build on it side
it avoid file lock for IDE for example
but this could also lead to error if the context for the restore is not exactly the same or for the run

if you can debug dotnet/tye by forming this repo you might found the root cause that way

I think one of the latest pr that was merged will help lots of edge case (may be yours) but it might not be release
you can take a look at the "ms build out of proc" if you're curious
if there's a nightly to test out for you

**Comment by Ganesh-Sattawan** [comment]
> > without tye Project is building and running , however not working with tye
> 
> yep dotnet/tye copy the project and redo the restore / build on it side
> it avoid file lock for IDE for example
> but this could also lead to error if the context for the restore is not exactly the same or for the run
> 
> if you can debug dotnet/tye by forking this repo you might found the root cause that way
> 
> I think one of the latest pr that was merged will help lots of edge case (may be yours) but it might not be release
> you can take a look at the "ms build out of proc" if you're curious
> if there's a nightly to test out for you

Thank you for your suggestions, i downloaded code locally and tried and it worked , so updated the installation to varsion 05.0 using command "dotnet tool update -g Microsoft.Tye --version "0.5.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
