### ISSUE TITLE
[.NET 5 RC2] WorkloadSdkResolver failed to load

### ISSUE THREAD

**Issue by davidhenley** [dotnet/tye#699]
### Describe the bug
Error with .NET 5 RC2. Project builds and runs when not launched by Tye and works with RC1.

### To Reproduce

`dotnet --version` 5.0.100-rc.2.20479.15
`tye --version` 0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243
`tye run`

### Further technical details

**Works**: when `global.json` is 

```
{
  "sdk": {
    "version": "5.0.100-rc.1.20452.10"
  }
}
```

**Doesn't work**: when `global.json` is 

```
{
  "sdk": {
    "version": "5.0.100-rc.2.20479.15"
  }
}
```

```
Locating .NET SDK...
Found .NET SDK at: /usr/local/share/dotnet/sdk/5.0.100-rc.2.20479.15/
Registered .NET SDK.Loading project '/Users/home/Desktop/Alpha-Monolith/src/Alpha.API/Alpha.API.csproj'.

Drats! 'run' failed:
        Failed to load project: '/Users/home/Desktop/Alpha-Monolith/src/Alpha.API/Alpha.API.csproj'.

Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK resolver type "WorkloadSdkResolver" failed to load. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  /Users/home/Desktop/Alpha-Monolith/src/Alpha.API/Alpha.API.csproj
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'


   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolvers(String resolverPath, LoggingContext loggingContext, ElementLocation location, List`1 resolvers)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.Initialize(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>n__0(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>c__DisplayClass3_0.<ResolveSdk>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.FromFile(String file, ProjectOptions options)
   at Microsoft.Tye.ProjectReader.EvaluateProject(OutputContext output, DotnetProjectServiceBuilder project) in /_/src/Microsoft.Tye.Core/ProjectReader.cs:line 166

```

**tye.yaml**:
```
name: alpha

extensions:
- name: seq

services:
- name: api
  project: src/Alpha.API/Alpha.API.csproj
  bindings:
    - port: 5000
      protocol: http
```

**Comment by jkotalik** [comment]
@JunTaoLuo we should release tye as soon as .NET 5 support works E2E.

This is currently fixed in master, if you'd like to use the latest nightlies, they will work with .NET 5 here: https://github.com/dotnet/tye/blob/master/docs/getting_started.md#working-with-ci-builds

**Comment by davidhenley** [comment]
Confirmed that works! Thanks @jkotalik

**Comment by jkotalik** [comment]
Awesome, closing for now then.

**Comment by msschl** [comment]
I had the same issue before switching to the nightly builds, thanks for the info 👍🏽

**Comment by Kralizek** [comment]
Is `0.5.0-*` containing the fix?

**Comment by tebeco** [comment]
@Kralizek best way to find out is to update, 0.5.0-* was released on github as it contains multiple fixes, maybe this one, fell free to use the latest version to check and do a feedback

**Comment by Kralizek** [comment]
@tebeco thanks. I ended up using the 0.6.0 from the nightly feed.

**Comment by tebeco** [comment]
that works too ^^
i was not sure if you preferred nightly of "controlled" on nuget ;)

**Comment by Kralizek** [comment]
I can run nightly until the next release :)

**Comment by r-bennett** [comment]
@jkotalik do you have any details on how this got fixed? Have been running into the same issue with some of our own tooling after installing .NET 5 SDKs

**Comment by jkotalik** [comment]
@JunTaoLuo may have more context, but the fix involved moving our calls to msbuild from in-process to out-of-process.

**Comment by r-bennett** [comment]
Thanks, looks like https://github.com/dotnet/tye/pull/674 was the fix
