### ISSUE TITLE
Exception while attempting to run sample app

### ISSUE THREAD

**Issue by syoguran** [dotnet/tye#764]
As described in [documentation](https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/00_run_locally.md), I tried to run the sample app on my local.

tye --version : 0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23
Platform Windows 10

## Full error message:
tye run -v debug
Loading Application Details...
Restoring and evaluating projects
Resolved metadata for service frontend at C:\Users\serka\Documents\Projects\sandbox\microservice\frontend\obj\Debug\netcoreapp3.1\MicrosoftTye.ProjectMetadata.txt
Resolved metadata for service backend at C:\Users\serka\Documents\Projects\sandbox\microservice\backend\obj\Debug\netcoreapp3.1\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 1156.0996ms
Found application version: 1.0.0
RunCommand=C:\Users\serka\Documents\Projects\sandbox\microservice\frontend\bin\Debug\netcoreapp3.1\frontend.exe
RunArguments=
TargetPath=C:\Users\serka\Documents\Projects\sandbox\microservice\frontend\bin\Debug\netcoreapp3.1\frontend.dll
PublishDir=bin\Debug\netcoreapp3.1\publish\
AssemblyName=frontend
IntermediateOutputPath=obj\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Parsed target framework name: netcoreapp
Parsed target framework version: 3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1.7953ms
Found application version: 1.0.0
RunCommand=C:\Users\serka\Documents\Projects\sandbox\microservice\backend\bin\Debug\netcoreapp3.1\backend.exe
RunArguments=
TargetPath=C:\Users\serka\Documents\Projects\sandbox\microservice\backend\bin\Debug\netcoreapp3.1\backend.dll
PublishDir=bin\Debug\netcoreapp3.1\publish\
AssemblyName=backend
IntermediateOutputPath=obj\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Parsed target framework name: netcoreapp
Parsed target framework version: 3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 0.6879ms
Launching Tye Host...

[14:36:03 INF] Executing application from C:\Users\serka\Documents\Projects\sandbox\microservice\microservice.sln
An unhandled exception has occurred, how unseemly:
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.Tye.Hosting.TyeHost.IsPortAlreadyInUse(Int32 port) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 244
   at Microsoft.Tye.Hosting.TyeHost.ComputePort(WebApplication app) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 225
   at Microsoft.Tye.Hosting.TyeHost.ConfigureApplication(WebApplication app) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 184
   at Microsoft.Tye.Hosting.TyeHost.StartAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 86
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 60
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 70
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__15_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__15_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by israels** [comment]
I'm having the same issue on my work (domain joined) machine.  It's possible some group policy is blocking communication and startup, but I don't know how to begin troubleshooting.

**Comment by bozhiqian** [comment]
Does anyone know if this issue has been resolved? 

I have the same issue for a web api app generated by VS2019 template for .net 5. 
This api app is just standard weather forcast api from the template without any change by me. 
As soon as I run tye from VScode terminal, I get error. 

`PS D:\Dev\temp3\demoapi> tye run -v debug
Loading Application Details...
Restoring and evaluating projects
Resolved metadata for service demoapi at D:\Dev\temp3\demoapi\demoapi\obj\Debug\net5.0\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 1204.1741ms
Found application version: 1.0.0
RunCommand=D:\Dev\temp3\demoapi\demoapi\bin\Debug\net5.0\demoapi.exe
RunArguments=
TargetPath=D:\Dev\temp3\demoapi\demoapi\bin\Debug\net5.0\demoapi.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=demoapi
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Parsed target framework name: net
Parsed target framework version: 5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 3.6032ms
Launching Tye Host...

An unhandled exception has occurred, how unseemly: 
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.Tye.Hosting.TyeHost.IsPortAlreadyInUse(Int32 port) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 258
   at Microsoft.Tye.Hosting.TyeHost.ComputePort(Nullable`1 port) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 242
   at Microsoft.Tye.Hosting.TyeHost.<>c__DisplayClass27_0.<BuildWebApplication>b__1(IWebHostBuilder builder) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 157
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.<>c__DisplayClass0_0.<ConfigureWebHostDefaults>b__0(IWebHostBuilder webHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at Microsoft.Tye.Hosting.TyeHost.BuildWebApplication(Application application, HostOptions options, ILogEventSink sink) in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 129 
   at Microsoft.Tye.Hosting.TyeHost.StartAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 86
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 70
   at Microsoft.Tye.Hosting.TyeHost.RunAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 80
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by bozhiqian** [comment]
I have figured it. The tye run on port 8000 but one of my app has been already running on my machine with the port 8000 so tye host won't be able to start. I would expect tye would be able to change on its default port number by user in future.

**Comment by onurcanyilmaz** [comment]
> I have figured it out. The tye run on port 8000 but one of my app has been already running on my machine with the port 8000 so tye host won't be able to start. I would expect tye would be able to change on its default port number by user in future.

Hi @bozhiqian, 
I've faced same issue. 
I've found solution that related problem

`tye run --port <your_port>`

By the way I've read this document
https://github.com/dotnet/tye/blob/main/docs/reference/schema.md

cheers
