### ISSUE TITLE
Dapr client InvokeMethodAsync() throws a gRPC error with Tye

### ISSUE THREAD

**Issue by dasiths** [dotnet/tye#765]
### Describe the bug
I am using the Dapr recipe (shown here https://github.com/dotnet/tye/blob/master/docs/recipes/dapr.md) to do a simple service-to-service invocation. The Dapr client fails on `InvokeMethodAsync` with a gRPC error.

### To Reproduce

```csharp
var result = await _daprClient.InvokeMethodAsync<MyResult>("myservice", "hello");
```

Stack Trace:
``` 
[orders_f5aa7016-d]: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Temporary Redirect")
[orders_f5aa7016-d]: at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, Metadata headers, CancellationToken cancellationToken)
[orders_f5aa7016-d]: at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsync(String appId, String methodName, Any data, HTTPExtension httpExtension, CancellationToken cancellationToken)
[orders_f5aa7016-d]: at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](String appId, String methodName, HTTPExtension httpExtension, CancellationToken cancellationToken)
```

I can directly hit the service via (http) postman and get a result back. I can find the dapr side car port via Tye dashboard.
> http://localhost:<dapr-port>/v1.0/invoke/myservice/method/hellow

This is the other service being invoked
```
namespace MyService.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class HelloController : ControllerBase
    {
        private readonly ILogger<HelloController> _logger;

        public MyServiceController(ILogger<HelloController> logger)
        {
            _logger = logger;
        }

        public ActionResult<MyResult> Get()
        {
            var sentence = "this is a test";
            _logger.LogInformation($"{GetType().Name} triggered");
            return new MyResult();
        }
    }
}
```

### Further technical details

- Include the output of `tye --version`: 0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows): Windows 10 Pro 2004

**Comment by dasiths** [comment]
I figured out why this happens.

It's because the ASPNET CORE service being invocated had the following
```
app.UseHttpsRedirection();
```
I guess the gRPC service had trouble communicating with it as a result. Is there a way to force Tye to only host the https endpoint for a service? If so I'm guessing the gRPC client will pick the right endpoint.

**Comment by rynowak** [comment]
Crosslinking to this issue on Dapr: https://github.com/dapr/dapr/issues/1242

Currently Dapr is designed to use unencrypted HTTP to communicate with the app, and it doesn't follow redirects (hence the error your saw).

I think the reason you're seeing a "Not found" after disabling the HTTP binding is because the Dapr extension knows that only HTTP will work and explicitly tries to wire that up: https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L28

In the short team we should at a minimum suggest how to work around this issue (disable HTTPS binding).

**Comment by rynowak** [comment]
@jkotalik @JunTaoLuo

**Comment by jkotalik** [comment]
Yeah that makes more sense for this error. Besides guidance, is there anything we can do to make HTTPS work here? Or maybe we can always remove the https endpoints for dapr?

**Comment by rynowak** [comment]
It might be good to remove the https endpoint for dapr and log something saying you did. 

What comes to mind for me is that suppressing https when Tye infers bindings seems good. When the user specified the bindings explicitly - it seems less-good. I don't think this code knows whether https was specified by the user or inferred.

Note that we don't currently support https in production. It's not really common in k8s scenarios to give every app its own cert.
