### ISSUE TITLE
Exception when stopping tye with CTRL+C

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#776]
### Describe the bug
Getting this:
[07:09:22 ERR] Error while shutting down
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.
   at Bedrock.Framework.TimerAwaitable.Stop()
   at Bedrock.Framework.Server.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Tye.Hosting.ProxyService.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/ProxyService.cs:line 190
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 319
Oh dear! Operation canceled.
### To Reproduce

tye run

let is start

CTRL+C

### Further technical details

- Include the output of `tye --version`
0.6.0-alpha.20559.2+c91e24cf224a8a74121614052885956092c5384f
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)

WSL2

.NET 5 

azsdke2e
azsdke2e2

**Comment by davidhenley** [comment]
Same

```
[11:21:53 ERR] Error while shutting down
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.
   at Bedrock.Framework.TimerAwaitable.Stop()
   at Bedrock.Framework.Server.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Tye.Hosting.ProxyService.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/ProxyService.cs:line 190
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 319

```

**Comment by jbarczyk** [comment]
It happens to me when using Tye with:
a) mix of .NET Core and .NET Framework applicationc
b) mix of .NET Core and container (from image e.g. mssqlserver) application

```
Error while shutting down
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.
   at Bedrock.Framework.TimerAwaitable.Stop()
   at Bedrock.Framework.Server.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Tye.Hosting.ProxyService.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/ProxyService.cs:line 190
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 319
Oh dear! Operation canceled.
```


```
> dotnet --version
5.0.101
```

```
> tye --version
0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23
```

**Comment by jkotalik** [comment]
Fix is in another project. Will update the package version if all goes well.

**Comment by jkotalik** [comment]
I've been trying to repro this exception all day today, with no luck. My hypothesis for a fix won't actually change the fact that an exception is thrown, just that the exception we care about will be thrown instead.

@jongio @ooeygui what apps were you using to repro this issue? Can you either let me give you a custom package for the bedrock framework or if its possible for me to repro this locally, getting that working.

**Comment by jongio** [comment]
You can repro with memealyzer. https://aka.ms/memealyzer

Call ./run.sh {BASENAME}, then CTRL+C

**Comment by mateusrodrigues** [comment]
Adding my two cents: this happens to me whenever I `Ctrl+C` with the Tye Dashboard open on the browser - I have tried closing the dashboard before exiting Tye and can confirm it exits gracefully. It always fails right after `Running docker command network rm tye_network_c4d731fc-8`. I always run with `tye run --watch`, btw.

**Comment by paulomorgado** [comment]
But it doesn't always happen when the dashboard is running.

**Comment by davidhenley** [comment]
Thank you!!

**Comment by jongio** [comment]
🕺

**Comment by jkotalik** [comment]
Seems like this is still reproing:

ProxyService.StopAsync() still throwing.

**Comment by jkotalik** [comment]
Catching AggregateException should fix it
