### ISSUE TITLE
allow shell commands for javascript projects (yarn/npm)

### ISSUE THREAD

**Issue by OneCyrus** [dotnet/tye#873]
the executable type doesn't allow to run npm/yarn commands as it expects native binaries. this is fine as long as there is a binary build artifact. in case of javascript applications there is no binary artifact. e.g. running yarn or npm requires a node or a shell binary with the executable type. so the obvious way would be to just specify this binary e.g. `executable: node yarn start`. unfortunately this doesn't work as tye expects the node binary to be in the working directory.

how about extending executable to allow an executable from the path search order? or a new type which would allow to execute a shell command?

**Comment by ans-ashkan** [comment]
I have the same issue with npm.

here is the error I receive when I run tye:
```
Loading Application Details...
Restoring and evaluating projects
Restore and project evaluation took: 350.4465ms
Launching Tye Host...

[15:27:47 INF] Executing application from C:\pro\Wallit\PingExchange\tye.front.yml
[15:27:47 INF] Dashboard running on http://127.0.0.1:8000
[15:27:47 INF] Launching service front-end_0604036d-c: npm run dev
[15:27:47 ERR] Failed to launch process for service front-end_0604036d-c
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 113
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
```

My tye file:
```
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
name: test
services:
- name: front-end
  executable: npm
  args: 'run dev'
  workingDirectory: ./Frontend/
  bindings:
  - port: 8082
    protocol: http
  env:
  - name: CONTOUR
    value: dev.local.tye
```

A workaround is to use cmd as executable and pass arguments to run npm, but that's not x-plat.

**Comment by OneCyrus** [comment]
the problem with cmd/pwsh and so is that it doesn't work at all. it tries to find e.g. the cmd.exe in the working directory.

**Comment by dalibormesaric** [comment]
This actually works if you do the following

```
- name: front-end
  executable: cmd
  args: '/c npm run dev'
```

but it will work only on Windows

**Comment by iskandersierra** [comment]
I had the same issue here.

My solution, in case someone needs to use it, meanwhile a more portable solution to this issue is delivered, was to use powershell to locate where `yarn/npm/...` is:

```powershell
> Get-Command yarn
C:\Program Files (x86)\Yarn\bin\yarn.cmd
```

Depending on how you did installed `yarn` (`npm install --global yarn`, `choco install yarn -y`, ...) it could be a different location.

In my case, I was using [`nx`](https://nx.dev) to setup the monorepo, so had to ask for:

```powershell
> Get-Command nx
C:\Users\.....\AppData\Local\Yarn\bin\nx.cmd
```

So I added this config to the `tye.yaml` file:

```yaml
services:
  - name: admin-api
    executable: "%LOCALAPPDATA%/Yarn/bin/nx.cmd"
    args: serve admin-api --watch
    bindings:
      - name: http
        port: 3100
        protocol: http
```

It would be great a search stage for `executable`, where depending on the OS, tye would use `Get-Command ${runInfo.executable}` or `which ${runInfo.executable}` to expand the actual path for the executable. I suppose around this line at [ApplicationFactory](https://github.com/dotnet/tye/blob/main/src/Microsoft.Tye.Core/ApplicationFactory.cs#L235)

**Comment by onionhammer** [comment]
This seems like somewhat low hanging fruit, since this works pretty much flawlessly except that 'executable' is difficult to make work cross-platform; "npm" will be in different places for different OSs/versions.
