### ISSUE TITLE
Random crashes in macOS test run

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#890]
https://dev.azure.com/dnceng/public/_build/results?buildId=947381&view=results
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Dispose(Boolean disposing)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Finalize()
=== COMMAND LINE ===
"/Users/runner/work/1/s/.dotnet/dotnet" exec --depsfile "/Users/runner/work/1/s/artifacts/bin/Microsoft.Tye.E2ETests/Release/netcoreapp3.1/Microsoft.Tye.E2ETest.deps.json" --runtimeconfig "/Users/runner/work/1/s/artifacts/bin/Microsoft.Tye.E2ETests/Release/netcoreapp3.1/Microsoft.Tye.E2ETest.runtimeconfig.json"  "/Users/runner/work/1/s/.packages/xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" "/Users/runner/work/1/s/artifacts/bin/Microsoft.Tye.E2ETests/Release/netcoreapp3.1/Microsoft.Tye.E2ETest.dll" -noautoreporters -xml "/Users/runner/work/1/s/artifacts/TestResults/Release/Microsoft.Tye.E2ETests_netcoreapp3.1_x64.xml" -html "/Users/runner/work/1/s/artifacts/TestResults/Release/Microsoft.Tye.E2ETests_netcoreapp3.1_x64.html"  > "/Users/runner/work/1/s/artifacts/log/Release/Microsoft.Tye.E2ETests_netcoreapp3.1_x64.log" 2>&1



```

**Comment by jkotalik** [comment]
I'm seeing this without tests now, we should investigate as I'm seeing it somewhat frequently causing tye to crash.
