### ISSUE TITLE
Accessing disposed timer on ctrl-c

### ISSUE THREAD

**Issue by ooeygui** [dotnet/tye#900]
### Describe the bug
When shutting down tye from the command line after running `tye run` using ctrl-c, a timer is used after dispaosal

### To Reproduce
```
tye run
ctrl-c
error
```
### Further technical details
```
[13:00:25 ERR] Error while shutting down
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Bedrock.Framework.TimerAwaitable'.
   at Bedrock.Framework.TimerAwaitable.Stop()
   at Bedrock.Framework.Server.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Tye.Hosting.ProxyService.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/ProxyService.cs:line 190
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 39
   at Microsoft.Tye.Hosting.AggregateApplicationProcessor.StopAsync(Application application) in /_/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs:line 49
   at Microsoft.Tye.Hosting.TyeHost.StopAsync() in /_/src/Microsoft.Tye.Hosting/TyeHost.cs:line 315
```
- Include the output of `tye --version`
- 0.6.0-alpha.21064.4+4bfccefe7da87f64ea0371879e3bc27b32fe2194

- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)
Windows

**Comment by jongio** [comment]
dupe? https://github.com/dotnet/tye/issues/776

**Comment by jkotalik** [comment]
Yeah, we will look into this soon.

**Comment by ooeygui** [comment]
Yep, sorry about that.
