### ISSUE TITLE
issues in tye yaml file name handling 

### ISSUE THREAD

**Issue by mharthoorn** [dotnet/tye#934]
Our goal was to create two tye.yaml files (one for staging and production), to make sure we don't accidentally connect to the wrong container registry. The steps below, will show you the errors/stack trace.

```
> tye --version
0.6.0-alpha.21070.5+a42e4463943e3136dbd1de38474d8d62b802797c

> tye run 
(Works as expected).

> tye init
> tye run tye.yaml
(Works as expected)

> ren tye.yaml staging.tye.yaml
$ tye run staging.tye.yaml
Loading Application Details...
Error parsing tye.yaml: (7, 1): Unexpected key "name" in tye.yaml.

(removed the line "name: myapp" in staging.tye.yaml)
> tye run staging.tye.yaml
Loading Application Details...
An unhandled exception has occurred, how unseemly:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tye.DockerCompose.DockerComposeParser.ParseServiceList(YamlMappingNode node, ConfigApplication app) in /_/src/Microsoft.Tye.Core/DockerCompose/DockerComposeParser.cs:line 153
   at Tye.DockerCompose.DockerComposeParser.Parse(YamlMappingNode node, ConfigApplication app) in /_/src/Microsoft.Tye.Core/DockerCompose/DockerComposeParser.cs:line 146
   at Tye.DockerCompose.DockerComposeParser.ParseConfigApplication() in /_/src/Microsoft.Tye.Core/DockerCompose/DockerComposeParser.cs:line 58
   at Microsoft.Tye.ConfigModel.ConfigFactory.FromDockerComposeYaml(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 116
   at Microsoft.Tye.ConfigModel.ConfigFactory.FromFile(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 31
   at Microsoft.Tye.ApplicationFactory.CreateAsync(OutputContext output, FileInfo source, String framework, ApplicationFactoryFilter filter) in /_/src/Microsoft.Tye.Core/ApplicationFactory.cs:line 30
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()   
```

**Comment by jkotalik** [comment]
Ah, yes this is definitely a bug. Will fix.
