### ISSUE TITLE
tye run --watch not working if machine username has spaces

### ISSUE THREAD

**Issue by abhisheksiddhu** [dotnet/tye#978]
### Describe the bug
It's very similar to #766, with the difference that in that case, it had a workaround by specifying the install location for tye to a place with no spaces

### To Reproduce
create a Blazor Server project in .net 5
run command `tye run --watch`

Got Exceptions? Include both the message and the stack trace
-->

❯ tye run --watch --debug
Loading Application Details...
Launching Tye Host...

[20:07:16 INF] Executing application from D:\Workspace\Repositories\catalyst\tye.yaml
[20:07:16 INF] Dashboard running on http://127.0.0.1:8000
[20:07:16 INF] Building projects
[20:07:19 INF] Launching service catalyst-api_237fd145-a: D:\Workspace\Repositories\catalyst\api\Catalyst.Api\bin\Debug\net5.0\Catalyst.Api.exe
[20:07:19 INF] Launching service support-admin_0f2aa80a-3: D:\Workspace\Repositories\catalyst\web-hosts\Catalyst.AspNetCore.SupportAdmin\bin\Debug\net5.0\Catalyst.AspNetCore.SupportAdmin.exe
[20:07:19 ERR] Failed to launch process for service support-admin_0f2aa80a-3
System.InvalidOperationException: Command dotnet msbuild "D:\Workspace\Repositories\catalyst\web-hosts\Catalyst.AspNetCore.SupportAdmin\Catalyst.AspNetCore.SupportAdmin.csproj" /p:_DotNetWatchListFile=C:\Users\Abhishek Siddhu\AppData\Local\Temp\estucpfa.bts /nologo /v:n /t:GenerateWatchList /p:DotNetWatchBuild=true /p:DesignTimeBuild=true /p:CustomAfterMicrosoftCommonTargets=C:\Users\Abhishek Siddhu\.dotnet\tools\.store\microsoft.tye\0.6.0-alpha.21070.5\microsoft.tye\0.6.0-alpha.21070.5\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets /p:CustomAfterMicrosoftCommonCrossTargetingTargets=C:\Users\Abhishek Siddhu\.dotnet\tools\.store\microsoft.tye\0.6.0-alpha.21070.5\microsoft.tye\0.6.0-alpha.21070.5\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets returned exit code 1
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 154
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory.CreateAsync(CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs:line 73
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, String replica, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs:line 42
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 385
[20:07:19 ERR] Failed to launch process for service catalyst-api_237fd145-a
System.InvalidOperationException: Command dotnet msbuild "D:\Workspace\Repositories\catalyst\api\Catalyst.Api\Catalyst.Api.csproj" /p:_DotNetWatchListFile=C:\Users\Abhishek Siddhu\AppData\Local\Temp\r0dtb0gd.abu /nologo /v:n /t:GenerateWatchList /p:DotNetWatchBuild=true /p:DesignTimeBuild=true /p:CustomAfterMicrosoftCommonTargets=C:\Users\Abhishek Siddhu\.dotnet\tools\.store\microsoft.tye\0.6.0-alpha.21070.5\microsoft.tye\0.6.0-alpha.21070.5\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets /p:CustomAfterMicrosoftCommonCrossTargetingTargets=C:\Users\Abhishek Siddhu\.dotnet\tools\.store\microsoft.tye\0.6.0-alpha.21070.5\microsoft.tye\0.6.0-alpha.21070.5\tools\netcoreapp3.1\any\Watch\assets\DotNetWatch.targets returned exit code 1
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 154
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Internal.MsBuildFileSetFactory.CreateAsync(CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs:line 73
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, String replica, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs:line 42
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 385
[20:07:20 INF] Tye Host is stopping...

### Further technical details

- Include the output of `tye --version` : 0.6.0-alpha.21070.5+a42e4463943e3136dbd1de38474d8d62b802797c
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows) : Windows

**Comment by jkotalik** [comment]
Yep, this is a bug.
