### ISSUE TITLE
tye run, Failed to load project, FileNotFound, System.Collections.Immutable, Version=5.0.0.0

### ISSUE THREAD

**Issue by morley38** [dotnet/tye#989]
### Describe the bug
tye run fails - "Failure to load project:" because it can't find System.Collections.Immutable, Version-5.0.0.0

### To Reproduce
What steps can we follow to reproduce the issue?
Install new version on Windows 10.  This was incidentally after updating Visual Studio to 10.9.2.

dotnet tool install -g Microsoft.Tye --version "0.2.0-alpha.20258.3"

Create a new multi-project solution in VS.  Solution built clean and template apps ran.  .Net core 5 Grpc and Web API templates - did not run in Docker but D-Desktop was up - no images currently running.

Ran tye init and then tye run.  Got the exceptions below.  Tried tye run again on each individual project with no difference.

Tried the same on a different Windows 10 PC.  No difference.
Tried a different solution with a single .Net core 3.1 Web API project - No difference.

Got Exceptions? Include both the message and the stack trace

C:\Users\chris.morley\source\repos\tpg.eventstream.typeregistry.ms\TypeRegistry>tye run
Loading Application Details...
Drats! 'run' failed:
        Failed to load project: 'C:\Users\chris.morley\source\repos\tpg.eventstream.typeregistry.ms\TypeRegistry\TypeRegistry.Command.Service\TypeRegistry.Command.Service.csproj'.

System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Build.Evaluation.Context.EvaluationContext..ctor(SharingPolicy policy, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Context.EvaluationContext.Create(SharingPolicy policy, MSBuildFileSystemBase fileSystem)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.FromFile(String file, ProjectOptions options)
   at Microsoft.Tye.ProjectReader.EvaluateProject(OutputContext output, ProjectServiceBuilder project) in /_/src/Microsoft.Tye.Core/ProjectReader.cs:line 166

### Further technical details
- Include the output of `tye --version`

C:\Users\chris.morley\source\repos\tpg.eventstream.typeregistry.ms\TypeRegistry>tye --version
0.2.0-alpha.20258.3+bf3bc0913b37e77f5f3ef14f409b3feb794cc447

- If possible rerun the command with `-v debug` and include the output
C:\Users\chris.morley\source\repos\tpg.eventstream.typeregistry.ms\TypeRegistry>tye run -v debug
Loading Application Details...
Drats! 'run' failed:
        Failed to load project: 'C:\Users\chris.morley\source\repos\tpg.eventstream.typeregistry.ms\TypeRegistry\TypeRegistry.Command.Service\TypeRegistry.Command.Service.csproj'.

System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Build.Evaluation.Context.EvaluationContext..ctor(SharingPolicy policy, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Context.EvaluationContext.Create(SharingPolicy policy, MSBuildFileSystemBase fileSystem)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.FromFile(String file, ProjectOptions options)
   at Microsoft.Tye.ProjectReader.EvaluateProject(OutputContext output, ProjectServiceBuilder project) in /_/src/Microsoft.Tye.Core/ProjectReader.cs:line 166

- The platform (Linux/macOS/Windows)
Windows 10

**Comment by jkotalik** [comment]
Can you update your version of tye? 0.2 didn't support 5.0.

**Comment by morley38** [comment]
Better.  I was following instructions on a blog post from Amiee (Introducing Project Tye | ASP.NET Blog (microsoft.com)<https://devblogs.microsoft.com/aspnet/introducing-project-tye/>) and didn’t notice how old it was.

My bad – thanks for the quick reply.

From: Justin Kotalik ***@***.***>
Date: Friday, March 19, 2021 at 5:09 PM
To: dotnet/tye ***@***.***>
Cc: Christopher Morley ***@***.***>, Author ***@***.***>
Subject: Re: [dotnet/tye] tye run, Failed to load project, FileNotFound, System.Collections.Immutable, Version=5.0.0.0 (#989)

Can you update your version of tye? 0.2 didn't support 5.0.
